// Automatically generated by forge bind-json.
pragma solidity >=0.6.2 <0.9.0;
pragma experimental ABIEncoderV2;

import {EIP712Types} from 'src/libraries/types/EIP712Types.sol';

interface Vm {
  function parseJsonTypeArray(
    string calldata json,
    string calldata key,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function parseJsonType(
    string calldata json,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function parseJsonType(
    string calldata json,
    string calldata key,
    string calldata typeDescription
  ) external pure returns (bytes memory);

  function serializeJsonType(
    string calldata typeDescription,
    bytes memory value
  ) external pure returns (string memory json);

  function serializeJsonType(
    string calldata objectKey,
    string calldata valueKey,
    string calldata typeDescription,
    bytes memory value
  ) external returns (string memory json);
}

library JsonBindings {
  Vm constant vm = Vm(address(uint160(uint256(keccak256('hevm cheat code')))));

  // prettier-ignore
  string constant schema_SetUserPositionManager = "SetUserPositionManager(address positionManager,address user,bool approve,uint256 nonce,uint256 deadline)";
  // prettier-ignore
  string constant schema_Permit = "Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)";

  function serialize(
    EIP712Types.SetUserPositionManager memory value
  ) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_SetUserPositionManager, abi.encode(value));
  }

  function serialize(
    EIP712Types.SetUserPositionManager memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return
      vm.serializeJsonType(objectKey, valueKey, schema_SetUserPositionManager, abi.encode(value));
  }

  function deserializeSetUserPositionManager(
    string memory json
  ) public pure returns (EIP712Types.SetUserPositionManager memory) {
    return
      abi.decode(
        vm.parseJsonType(json, schema_SetUserPositionManager),
        (EIP712Types.SetUserPositionManager)
      );
  }

  function deserializeSetUserPositionManager(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetUserPositionManager memory) {
    return
      abi.decode(
        vm.parseJsonType(json, path, schema_SetUserPositionManager),
        (EIP712Types.SetUserPositionManager)
      );
  }

  function deserializeSetUserPositionManagerArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.SetUserPositionManager[] memory) {
    return
      abi.decode(
        vm.parseJsonTypeArray(json, path, schema_SetUserPositionManager),
        (EIP712Types.SetUserPositionManager[])
      );
  }

  function serialize(EIP712Types.Permit memory value) internal pure returns (string memory) {
    return vm.serializeJsonType(schema_Permit, abi.encode(value));
  }

  function serialize(
    EIP712Types.Permit memory value,
    string memory objectKey,
    string memory valueKey
  ) internal returns (string memory) {
    return vm.serializeJsonType(objectKey, valueKey, schema_Permit, abi.encode(value));
  }

  function deserializePermit(string memory json) public pure returns (EIP712Types.Permit memory) {
    return abi.decode(vm.parseJsonType(json, schema_Permit), (EIP712Types.Permit));
  }

  function deserializePermit(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Permit memory) {
    return abi.decode(vm.parseJsonType(json, path, schema_Permit), (EIP712Types.Permit));
  }

  function deserializePermitArray(
    string memory json,
    string memory path
  ) public pure returns (EIP712Types.Permit[] memory) {
    return abi.decode(vm.parseJsonTypeArray(json, path, schema_Permit), (EIP712Types.Permit[]));
  }
}
