// SPDX-License-Identifier: UNLICENSED
// Copyright (c) 2025 Aave Labs
pragma solidity ^0.8.0;

import {Test} from 'forge-std/Test.sol';

import {BytecodeLoader} from 'tests/utils/BytecodeLoader.sol';

contract GenerateBytecodeScript is Test {
  string private constant HUB_BYTECODE_PATH = 'tests/bin/hub.bytecode';
  string private constant SPOKE_INSTANCE_BYTECODE_PATH = 'tests/bin/spokeInstance.bytecode';

  function test_generated_HubBytecode() public view {
    bytes memory hubBytecode = vm.getCode('src/hub/Hub.sol:Hub');

    assertEq(
      hubBytecode,
      BytecodeLoader.loadHubBytecode(),
      'Loaded Hub bytecode does not match generated bytecode'
    );
  }

  function test_generated_SpokeInstanceBytecode() public view {
    bytes memory spokeInstanceBytecode = vm.getCode(
      'src/spoke/instances/SpokeInstance.sol:SpokeInstance'
    );

    assertEq(
      spokeInstanceBytecode,
      BytecodeLoader.loadSpokeInstanceBytecode(),
      'Loaded SpokeInstance bytecode does not match generated bytecode'
    );
  }
}
