// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

library Hubs {
  address internal constant CORE_HUB = 0xCca852Bc40e560adC3b1Cc58CA5b55638ce826c9;
  address internal constant PLUS_HUB = 0x06002e9c4412CB7814a791eA3666D905871E536A;
  address internal constant PRIME_HUB = 0x943827DCA022D0F354a8a8c332dA1e5Eb9f9F931;
}

library Spokes {
  address internal constant BLUECHIP_SPOKE = 0x973a023A77420ba610f06b3858aD991Df6d85A08;
  address internal constant ETHENA_CORRELATED_SPOKE = 0x58131E79531caB1d52301228d1f7b842F26B9649;
  address internal constant ETHENA_ECOSYSTEM_SPOKE = 0xba1B3D55D249692b669A164024A838309B7508AF;
  address internal constant ETHERFI_ESPOKE = 0xbF10BDfE177dE0336aFD7fcCF80A904E15386219;
  address internal constant FOREX_SPOKE = 0xD8B93635b8C6d0fF98CbE90b5988E3F2d1Cd9da1;
  address internal constant GOLD_SPOKE = 0x65407b940966954b23dfA3caA5C0702bB42984DC;
  address internal constant KELP_ESPOKE = 0x3131FE68C4722e726fe6B2819ED68e514395B9a4;
  address internal constant LIDO_ESPOKE = 0xe1900480ac69f0B296841Cd01cC37546d92F35Cd;
  address internal constant LOMBARD_BTC_SPOKE = 0x7EC68b5695e803e98a21a9A05d744F28b0a7753D;
  address internal constant MAIN_SPOKE = 0x94e7A5dCbE816e498b89aB752661904E2F56c485;
}

library IrStrategies {
  address internal constant CORE_HUB = 0xAD88791B0F81D1FA242f637eB05bee0cbc53fe2f;
  address internal constant PLUS_HUB = 0x31280650661b8443723fa9739b3A164E3696af48;
  address internal constant PRIME_HUB = 0xDCd924047a4bDBFef9CCDDe845E5D45373Ad276D;
}

library Oracles {
  address internal constant BLUECHIP_SPOKE = 0xdA1266a7b8620819dAE3F8bd6B546Da36e505bB8;
  address internal constant ETHENA_CORRELATED_SPOKE = 0x9b91a0943CADf554742E8Fb358B1cC4ae4F85F01;
  address internal constant ETHENA_ECOSYSTEM_SPOKE = 0xc390dbe9fc00D6db73C52d375642b47008C33c90;
  address internal constant ETHERFI_ESPOKE = 0xd8B153FaAA8f2b1bC774916FEd333A4F3dE48792;
  address internal constant FOREX_SPOKE = 0xB3CE6E7b6d389a66eA4a3777bA07219d00FB3a9D;
  address internal constant GOLD_SPOKE = 0x0083421fd178749af2201ddA5A7C3feB5790B80c;
  address internal constant KELP_ESPOKE = 0x37C316996C714Bf906743071e04E62220b3271ac;
  address internal constant LIDO_ESPOKE = 0x664D73b6C3591333Fd79510f7ce9ef81228824F5;
  address internal constant LOMBARD_BTC_SPOKE = 0x198Cac7f54FFc7d709Ac0FEc4B6454CE73e21D3D;
  address internal constant MAIN_SPOKE = 0x99B2B6CEa9C3D2fd8F4d90f86741C44B212a6127;
}

library Tokens {
  address internal constant AAVE = 0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9;
  address internal constant EURC = 0x1aBaEA1f7C830bD89Acc67eC4af516284b1bC33c;
  address internal constant GHO = 0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f;
  address internal constant LBTC = 0x8236a87084f8B84306f72007F36F2618A5634494;
  address internal constant LINK = 0x514910771AF9Ca656af840dff83E8264EcF986CA;
  address internal constant PT_USDE_7MAY2026 = 0xAeBf0Bb9f57E89260d57f31AF34eB58657d96Ce0;
  address internal constant PT_sUSDE_7MAY2026 = 0x3de0ff76E8b528C092d47b9DaC775931cef80F49;
  address internal constant RLUSD = 0x8292Bb45bf1Ee4d140127049757C2E0fF06317eD;
  address internal constant USDC = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
  address internal constant USDG = 0xe343167631d89B6Ffc58B88d6b7fB0228795491D;
  address internal constant USDT = 0xdAC17F958D2ee523a2206206994597C13D831ec7;
  address internal constant USDe = 0x4c9EDD5852cd905f086C759E8383e09bff1E68B3;
  address internal constant WBTC = 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599;
  address internal constant WETH = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;
  address internal constant XAUt = 0x68749665FF8D2d112Fa859AA293F07A622782F38;
  address internal constant cbBTC = 0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf;
  address internal constant frxUSD = 0xCAcd6fd266aF91b8AeD52aCCc382b4e165586E29;
  address internal constant rsETH = 0xA1290d69c65A6Fe4DF752f95823fae25cB99e5A7;
  address internal constant sUSDe = 0x9D39A5DE30e57443BfF2A8307A4256c8797A3497;
  address internal constant weETH = 0xCd5fE23C85820F7B72D0926FC9b05b43E359b7ee;
  address internal constant wstETH = 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0;
}

library Infra {
  address internal constant HUB_CONFIGURATOR = 0x1F0753480bB03EaA00863224602267B7E0525C3d;
  address internal constant SPOKE_CONFIGURATOR = 0x9BFFf48BFb5A7AE70c348d4d4cb97E8DEFa5389a;
  address internal constant ACCESS_MANAGER = 0x08aE3BE30958cDd1847ec58fFfd4C451a87fDF01;
  address internal constant CONFIG_POSITION_MANAGER = 0x51305839CE822a7b4b12AA7D86eA7005052d575c;
  address internal constant GIVER_POSITION_MANAGER = 0x17A54b8d6D9C68e7fa1C7112AC998EA1BA51d11e;
  address internal constant TAKER_POSITION_MANAGER = 0x6c044c0D3801499bCAbfAd458B70880bc518e9F7;
  address internal constant NATIVE_TOKEN_GATEWAY = 0xe68ab4F90Fe026B9873F5F276eD2d7efBbbE42Be;
  address internal constant SIGNATURE_GATEWAY = 0xfbC184337Dc6595D8bf62968Bda46e7De7AF9c3d;
  address internal constant TREASURY_SPOKE = 0xB9B0b8616f6Bf6841972a52058132BE08d723155;
}
