// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

library Hubs {
  address internal constant CORE_HUB = 0x630c2cFF89cb11E62dE047EaeD8C4B396906bD7D;
  address internal constant PLUS_HUB = 0x903395aEF788bD0A3a4c7a08651a9115add7c36b;
  address internal constant PRIME_HUB = 0xf64d97bd0454DF721d0edB468265f204D3A3421D;
}

library Spokes {
  address internal constant BLUECHIP_SPOKE = 0xF1Fa1042474dC8bd4Ef830Fe70aE22C85A326729;
  address internal constant ETHENA_CORRELATED_SPOKE = 0xa1A984B65b661599a61680f56a6c864ECED96CA6;
  address internal constant ETHENA_ECOSYSTEM_SPOKE = 0x417Fae379865b8E298332e2F6fdcc2526D55a090;
  address internal constant ETHERFI_ESPOKE = 0x7ED7431793eCbe5d42D64CA9b2593d026beB051B;
  address internal constant FOREX_SPOKE = 0x37b36B7dfaBB69B12519B7Faaf019a6C0B261264;
  address internal constant GOLD_SPOKE = 0x332EFa0E2121091Ae94f44F8c2C383B061ae2Ea7;
  address internal constant KELP_ESPOKE = 0xC8FA3983843E7a978244e34c0e2562159A3D0783;
  address internal constant LIDO_ESPOKE = 0xa9Dd188591A6F0C92bD1dC3A461a64c188694FB3;
  address internal constant LOMBARD_BTC_SPOKE = 0xc78F5e5566C9Bde0C531fC8c7F5dC5954daFcA9e;
  address internal constant MAIN_SPOKE = 0x6488A415e9eA693EC7Ef32579507e1907c0AC798;
}

library IrStrategies {
  address internal constant CORE_HUB = 0x4520172Ac74F62a7e07a9d1E8D1Ec29431F978B4;
  address internal constant PLUS_HUB = 0xC9E8988C595e8754Fa245aAF3D2b3Ee10D9067bD;
  address internal constant PRIME_HUB = 0xdD771f02c61d87289c3e80092Cf49fF66b5060f3;
}

library Oracles {
  address internal constant BLUECHIP_SPOKE = 0xb113DD155B036d402Ab146866EaCBD8ec57e0CB4;
  address internal constant ETHENA_CORRELATED_SPOKE = 0x779F5c43981FF994E745088e43cf1Be3EfE7277A;
  address internal constant ETHENA_ECOSYSTEM_SPOKE = 0x3554a2a711D3b4aA91592BE484ef5Eb93DA06B6A;
  address internal constant ETHERFI_ESPOKE = 0xcd8969028aEf5A787378198bDb3aD1afae44Ba0f;
  address internal constant FOREX_SPOKE = 0x99DDd6F3012CF551689Df85A090a14d4f190fd66;
  address internal constant GOLD_SPOKE = 0x9bE2cE60a1C2223C208cE06Bbd1617C9eA5a54f2;
  address internal constant KELP_ESPOKE = 0xDEE757AEC0096399B1de3f56E2D689d7Df12168d;
  address internal constant LIDO_ESPOKE = 0xeC3D47016536De544bc3b53C49175549Dc6b52C0;
  address internal constant LOMBARD_BTC_SPOKE = 0x35156282022DfEB5b164ea2cbf6EF521CB8A0b5f;
  address internal constant MAIN_SPOKE = 0x801A01dBF24eD0F2b48AD6aaB8613b45711D21f0;
}

library Tokens {
  address internal constant AAVE = 0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9;
  address internal constant EURC = 0x1aBaEA1f7C830bD89Acc67eC4af516284b1bC33c;
  address internal constant GHO = 0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f;
  address internal constant LBTC = 0x8236a87084f8B84306f72007F36F2618A5634494;
  address internal constant LINK = 0x514910771AF9Ca656af840dff83E8264EcF986CA;
  address internal constant PT_USDe = 0xAeBf0Bb9f57E89260d57f31AF34eB58657d96Ce0;
  address internal constant PT_sUSDe = 0x3de0ff76E8b528C092d47b9DaC775931cef80F49;
  address internal constant RLUSD = 0x8292Bb45bf1Ee4d140127049757C2E0fF06317eD;
  address internal constant USDC = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
  address internal constant USDG = 0xe343167631d89B6Ffc58B88d6b7fB0228795491D;
  address internal constant USDT = 0xdAC17F958D2ee523a2206206994597C13D831ec7;
  address internal constant USDe = 0x4c9EDD5852cd905f086C759E8383e09bff1E68B3;
  address internal constant WBTC = 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599;
  address internal constant WETH = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;
  address internal constant XAUt = 0x68749665FF8D2d112Fa859AA293F07A622782F38;
  address internal constant cbBTC = 0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf;
  address internal constant frxUSD = 0xCAcd6fd266aF91b8AeD52aCCc382b4e165586E29;
  address internal constant rsETH = 0xA1290d69c65A6Fe4DF752f95823fae25cB99e5A7;
  address internal constant sUSDe = 0x9D39A5DE30e57443BfF2A8307A4256c8797A3497;
  address internal constant weETH = 0xCd5fE23C85820F7B72D0926FC9b05b43E359b7ee;
  address internal constant wstETH = 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0;
}

library Infra {
  address internal constant HUB_CONFIGURATOR = 0xE63b9229Dcea75f2D5193eC876E59C00F339c134;
  address internal constant SPOKE_CONFIGURATOR = 0x9F690Cf64b87Dce2e9CE60650d1f570cd15dEB11;
  address internal constant ACCESS_MANAGER = 0x70e05E3Bc4F37B7d096B14D51D610D098B96262d;
  address internal constant CONFIG_POSITION_MANAGER = 0x081454BA40dB1a7CBd42F763AdE36d8ffAEB8913;
  address internal constant GIVER_POSITION_MANAGER = 0x96795f26b1B70c7908f959862e7cBBbBd72B96cd;
  address internal constant TAKER_POSITION_MANAGER = 0x1A2cc52338ab89231d0FF7D9530759F6C3fdB7eA;
  address internal constant NATIVE_TOKEN_GATEWAY = 0xB79Cf8E8ec9cbf8D93eeD85a4Eea06fA2D78Dae0;
  address internal constant SIGNATURE_GATEWAY = 0xa57b66798942c85c81DCf4FC83E8732a92729330;
  address internal constant TREASURY_SPOKE = 0x795Faf19DE8be50575623d5c732408a4669B0096;
}
