// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

library Hubs {
  address internal constant CORE_HUB = 0x94B33734C67409816Df02994BF648d62310e5dAE;
  address internal constant PLUS_HUB = 0x2CE890e39020F5FCA1BAEA4aC57222acA36Bb0E9;
  address internal constant PRIME_HUB = 0x92434157Bb548F9648bA69b816E1ea9f820A06C1;
}

library Spokes {
  address internal constant BLUECHIP_SPOKE = 0x38905FB8b5474704602976CA9Ab9C3986Acc3031;
  address internal constant ETHENA_CORRELATED_SPOKE = 0x5cB4875cbE09C462c8FDE663e41be6418fBD85Ab;
  address internal constant ETHENA_ECOSYSTEM_SPOKE = 0x3FE862d6Cbb3712AA7d457D34882cE777c409f66;
  address internal constant ETHERFI_ESPOKE = 0xD4F6dE2aC6370B5A29512918A502b8bA7A67d7D8;
  address internal constant FOREX_SPOKE = 0xD78a7285005D821468F7862eE0e9E80219E88Ff4;
  address internal constant GOLD_SPOKE = 0xD088870248ec87df2E0C6bd07719e4ae624F4FF2;
  address internal constant KELP_ESPOKE = 0x2A8362a4031F29997fBEe017c15CDd3F98087Ab5;
  address internal constant LIDO_ESPOKE = 0xb107B929a49889cC7765052358bBAA9a52B14294;
  address internal constant LOMBARD_BTC_SPOKE = 0x72A008c6b0137827351897b4c6C4e7Ab1180A38f;
  address internal constant MAIN_SPOKE = 0x206D960e7522168CAaf1c9941Bd0d2942C5775Ee;
}

library IrStrategies {
  address internal constant CORE_HUB = 0x112161974F53Cc0C1a1480dbbE05bDfd3817A588;
  address internal constant PLUS_HUB = 0x3994b60b022005750f44D310A13F637edAE0ba59;
  address internal constant PRIME_HUB = 0x7F0CF218f98d915B50208e7D08a4471A0ECbe40a;
}

library Oracles {
  address internal constant BLUECHIP_SPOKE = 0xC1cfdaBC3ECC3b0B2C2Df87daD9F005A4A316a8c;
  address internal constant ETHENA_CORRELATED_SPOKE = 0xA8a747E8802d23560013cE6E2F76FE635aCe42fd;
  address internal constant ETHENA_ECOSYSTEM_SPOKE = 0x8049280b91eF79A9f70c66627f462D6b4C1bCf0F;
  address internal constant ETHERFI_ESPOKE = 0xE592273382f738DAB1F1da923c599A73f2f578d2;
  address internal constant FOREX_SPOKE = 0x3AbAdCe3aCbdF9614A8758d7CC1482D9778A9713;
  address internal constant GOLD_SPOKE = 0xE1eE04E70e4De25ba4409ee3a312b973407aCdcd;
  address internal constant KELP_ESPOKE = 0xED40B669bbb3EC0597fD6F8Dd6611dA3A22014f8;
  address internal constant LIDO_ESPOKE = 0xdad20a80C88CAf955b86f83eDF589CEf09B24ba0;
  address internal constant LOMBARD_BTC_SPOKE = 0x9F88aE2b024718D5BD6A00A7E7c443EE04916FB7;
  address internal constant MAIN_SPOKE = 0x3c967c6E6fdB1Ef192C0b3869152A8B64148A0B9;
}

library Tokens {
  address internal constant AAVE = 0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9;
  address internal constant EURC = 0x1aBaEA1f7C830bD89Acc67eC4af516284b1bC33c;
  address internal constant GHO = 0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f;
  address internal constant LBTC = 0x8236a87084f8B84306f72007F36F2618A5634494;
  address internal constant LINK = 0x514910771AF9Ca656af840dff83E8264EcF986CA;
  address internal constant PT_USDE_7MAY2026 = 0xAeBf0Bb9f57E89260d57f31AF34eB58657d96Ce0;
  address internal constant PT_sUSDE_7MAY2026 = 0x3de0ff76E8b528C092d47b9DaC775931cef80F49;
  address internal constant RLUSD = 0x8292Bb45bf1Ee4d140127049757C2E0fF06317eD;
  address internal constant USDC = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
  address internal constant USDG = 0xe343167631d89B6Ffc58B88d6b7fB0228795491D;
  address internal constant USDT = 0xdAC17F958D2ee523a2206206994597C13D831ec7;
  address internal constant USDe = 0x4c9EDD5852cd905f086C759E8383e09bff1E68B3;
  address internal constant WBTC = 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599;
  address internal constant WETH = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;
  address internal constant XAUt = 0x68749665FF8D2d112Fa859AA293F07A622782F38;
  address internal constant cbBTC = 0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf;
  address internal constant frxUSD = 0xCAcd6fd266aF91b8AeD52aCCc382b4e165586E29;
  address internal constant rsETH = 0xA1290d69c65A6Fe4DF752f95823fae25cB99e5A7;
  address internal constant sUSDe = 0x9D39A5DE30e57443BfF2A8307A4256c8797A3497;
  address internal constant weETH = 0xCd5fE23C85820F7B72D0926FC9b05b43E359b7ee;
  address internal constant wstETH = 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0;
}

library Infra {
  address internal constant HUB_CONFIGURATOR = 0xceF48d919fE6D1f4A6AeFBD1acE2b5f3caCD9246;
  address internal constant SPOKE_CONFIGURATOR = 0x560D5789e90C8bEd6Ac00ac06cF88263013695FA;
  address internal constant ACCESS_MANAGER = 0x4287339f30A60b45886CeB4B5509e000b9C4ae2E;
  address internal constant CONFIG_POSITION_MANAGER = 0x2114e11B1bCDc4bE145b9B3A56D3DEF033bCED86;
  address internal constant GIVER_POSITION_MANAGER = 0x26387Ebb8Eb131CC2Db65a74396107e2426Bfa0C;
  address internal constant TAKER_POSITION_MANAGER = 0x58547331fA03De7BcB9441a07E02a1Ec43532c81;
  address internal constant NATIVE_TOKEN_GATEWAY = 0x8D449B653c7188A4f997439Bb8FAB6f4A46d8720;
  address internal constant SIGNATURE_GATEWAY = 0xf209d903C783f227c51b4A001DB9C1BDE7d50185;
  address internal constant TREASURY_SPOKE = 0x378A1C5FdC2242DDCA471E5E1F0c274e26250238;
}
