// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {ISpokeConfigurator} from 'src/spoke/interfaces/ISpokeConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';
import {ISpoke} from 'src/spoke/interfaces/ISpoke.sol';
import {IAssetInterestRateStrategy} from 'src/hub/interfaces/IAssetInterestRateStrategy.sol';

import {Hubs, Spokes, Tokens, IrStrategies, Infra} from './AaveV4Contracts.sol';

contract ConfigPayload_4_SpokePositionManagerUpdates is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function spokePositionManagerUpdates()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.PositionManagerUpdate[] memory updates)
  {
    updates = new IAaveV4ConfigEngine.PositionManagerUpdate[](50);
    updates[0] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      active: true
    });
    updates[1] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      positionManager: Infra.GIVER_POSITION_MANAGER,
      active: true
    });
    updates[2] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      positionManager: Infra.TAKER_POSITION_MANAGER,
      active: true
    });
    updates[3] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      positionManager: Infra.SIGNATURE_GATEWAY,
      active: true
    });
    updates[4] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      active: true
    });
    updates[5] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LIDO_ESPOKE,
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      active: true
    });
    updates[6] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LIDO_ESPOKE,
      positionManager: Infra.GIVER_POSITION_MANAGER,
      active: true
    });
    updates[7] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LIDO_ESPOKE,
      positionManager: Infra.TAKER_POSITION_MANAGER,
      active: true
    });
    updates[8] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LIDO_ESPOKE,
      positionManager: Infra.SIGNATURE_GATEWAY,
      active: true
    });
    updates[9] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LIDO_ESPOKE,
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      active: true
    });
    updates[10] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHERFI_ESPOKE,
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      active: true
    });
    updates[11] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHERFI_ESPOKE,
      positionManager: Infra.GIVER_POSITION_MANAGER,
      active: true
    });
    updates[12] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHERFI_ESPOKE,
      positionManager: Infra.TAKER_POSITION_MANAGER,
      active: true
    });
    updates[13] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHERFI_ESPOKE,
      positionManager: Infra.SIGNATURE_GATEWAY,
      active: true
    });
    updates[14] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHERFI_ESPOKE,
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      active: true
    });
    updates[15] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.KELP_ESPOKE,
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      active: true
    });
    updates[16] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.KELP_ESPOKE,
      positionManager: Infra.GIVER_POSITION_MANAGER,
      active: true
    });
    updates[17] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.KELP_ESPOKE,
      positionManager: Infra.TAKER_POSITION_MANAGER,
      active: true
    });
    updates[18] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.KELP_ESPOKE,
      positionManager: Infra.SIGNATURE_GATEWAY,
      active: true
    });
    updates[19] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.KELP_ESPOKE,
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      active: true
    });
    updates[20] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      active: true
    });
    updates[21] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      positionManager: Infra.GIVER_POSITION_MANAGER,
      active: true
    });
    updates[22] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      positionManager: Infra.TAKER_POSITION_MANAGER,
      active: true
    });
    updates[23] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      positionManager: Infra.SIGNATURE_GATEWAY,
      active: true
    });
    updates[24] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      active: true
    });
    updates[25] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      active: true
    });
    updates[26] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      positionManager: Infra.GIVER_POSITION_MANAGER,
      active: true
    });
    updates[27] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      positionManager: Infra.TAKER_POSITION_MANAGER,
      active: true
    });
    updates[28] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      positionManager: Infra.SIGNATURE_GATEWAY,
      active: true
    });
    updates[29] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      active: true
    });
    updates[30] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      active: true
    });
    updates[31] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      positionManager: Infra.GIVER_POSITION_MANAGER,
      active: true
    });
    updates[32] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      positionManager: Infra.TAKER_POSITION_MANAGER,
      active: true
    });
    updates[33] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      positionManager: Infra.SIGNATURE_GATEWAY,
      active: true
    });
    updates[34] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      active: true
    });
    updates[35] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      active: true
    });
    updates[36] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      positionManager: Infra.GIVER_POSITION_MANAGER,
      active: true
    });
    updates[37] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      positionManager: Infra.TAKER_POSITION_MANAGER,
      active: true
    });
    updates[38] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      positionManager: Infra.SIGNATURE_GATEWAY,
      active: true
    });
    updates[39] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      active: true
    });
    updates[40] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      active: true
    });
    updates[41] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      positionManager: Infra.GIVER_POSITION_MANAGER,
      active: true
    });
    updates[42] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      positionManager: Infra.TAKER_POSITION_MANAGER,
      active: true
    });
    updates[43] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      positionManager: Infra.SIGNATURE_GATEWAY,
      active: true
    });
    updates[44] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      active: true
    });
    updates[45] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      active: true
    });
    updates[46] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      positionManager: Infra.GIVER_POSITION_MANAGER,
      active: true
    });
    updates[47] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      positionManager: Infra.TAKER_POSITION_MANAGER,
      active: true
    });
    updates[48] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      positionManager: Infra.SIGNATURE_GATEWAY,
      active: true
    });
    updates[49] = IAaveV4ConfigEngine.PositionManagerUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      active: true
    });
    return updates;
  }
}
