// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {ISpokeConfigurator} from 'src/spoke/interfaces/ISpokeConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';
import {ISpoke} from 'src/spoke/interfaces/ISpoke.sol';
import {IAssetInterestRateStrategy} from 'src/hub/interfaces/IAssetInterestRateStrategy.sol';

import {Hubs, Spokes, Tokens, IrStrategies, Infra} from './AaveV4Contracts.sol';

contract ConfigPayload_1b_HubAssetListings is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function hubAssetListings()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.AssetListing[] memory listings)
  {
    listings = new IAaveV4ConfigEngine.AssetListing[](11);
    listings[0] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WBTC,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 8000,
        baseDrawnRate: 25,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 6000
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Core WBTC',
        symbol: 'aCore-WBTC'
      })
    });
    listings[1] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.cbBTC,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 8000,
        baseDrawnRate: 25,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 6000
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Core cbBTC',
        symbol: 'aCore-cbBTC'
      })
    });
    listings[2] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.LBTC,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Core LBTC',
        symbol: 'aCore-LBTC'
      })
    });
    listings[3] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.XAUt,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Core XAUt',
        symbol: 'aCore-XAUt'
      })
    });
    listings[4] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.AAVE,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Core AAVE',
        symbol: 'aCore-AAVE'
      })
    });
    listings[5] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.LINK,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Core LINK',
        symbol: 'aCore-LINK'
      })
    });
    listings[6] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.WETH,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Prime WETH',
        symbol: 'aPrime-WETH'
      })
    });
    listings[7] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.WBTC,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Prime WBTC',
        symbol: 'aPrime-WBTC'
      })
    });
    listings[8] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.cbBTC,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Prime cbBTC',
        symbol: 'aPrime-cbBTC'
      })
    });
    listings[9] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.wstETH,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Prime wstETH',
        symbol: 'aPrime-wstETH'
      })
    });
    listings[10] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.USDC,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 2000
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 37500,
        name: 'Tokenized Aave Prime USDC',
        symbol: 'aPrime-USDC'
      })
    });
    return listings;
  }
}
