// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {ISpokeConfigurator} from 'src/spoke/interfaces/ISpokeConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';
import {ISpoke} from 'src/spoke/interfaces/ISpoke.sol';
import {IAssetInterestRateStrategy} from 'src/hub/interfaces/IAssetInterestRateStrategy.sol';

import {Hubs, Spokes, Tokens, IrStrategies, Infra} from './AaveV4Contracts.sol';

contract ConfigPayload_2_HubSpokeRegistrations is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function hubSpokeToAssetsAdditions()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.SpokeToAssetsAddition[] memory additions)
  {
    additions = new IAaveV4ConfigEngine.SpokeToAssetsAddition[](12);
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](14);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 1500,
          drawCap: 130,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.wstETH,
        config: IHub.SpokeConfig({
          addCap: 229,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[2] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.weETH,
        config: IHub.SpokeConfig({
          addCap: 58,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[3] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WBTC,
        config: IHub.SpokeConfig({
          addCap: 16,
          drawCap: 1,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[4] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.cbBTC,
        config: IHub.SpokeConfig({
          addCap: 13,
          drawCap: 1,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[5] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.AAVE,
        config: IHub.SpokeConfig({
          addCap: 5000,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[6] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.LINK,
        config: IHub.SpokeConfig({
          addCap: 31250,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[7] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 1250000,
          drawCap: 1250000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[8] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 1250000,
          drawCap: 1250000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[9] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.EURC,
        config: IHub.SpokeConfig({
          addCap: 225000,
          drawCap: 150000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[10] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.RLUSD,
        config: IHub.SpokeConfig({
          addCap: 500000,
          drawCap: 340000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[11] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDG,
        config: IHub.SpokeConfig({
          addCap: 500000,
          drawCap: 340000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[12] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.frxUSD,
        config: IHub.SpokeConfig({
          addCap: 500000,
          drawCap: 312500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[13] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 500000,
          drawCap: 500000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[0] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: Spokes.MAIN_SPOKE,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](2);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.wstETH,
        config: IHub.SpokeConfig({
          addCap: 406,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 441,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[1] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: Spokes.LIDO_ESPOKE,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](2);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.weETH,
        config: IHub.SpokeConfig({
          addCap: 500,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 530,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[2] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: Spokes.ETHERFI_ESPOKE,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](2);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.rsETH,
        config: IHub.SpokeConfig({
          addCap: 563,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 588,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[3] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: Spokes.KELP_ESPOKE,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](3);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.LBTC,
        config: IHub.SpokeConfig({
          addCap: 9,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 5,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[2] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.cbBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 3,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[4] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: Spokes.LOMBARD_BTC_SPOKE,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](8);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.XAUt,
        config: IHub.SpokeConfig({
          addCap: 125,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 125000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[2] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.RLUSD,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 62500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[3] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDG,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 62500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[4] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.frxUSD,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 62500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[5] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.EURC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 50000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[6] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 62500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[7] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 125000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[5] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: Spokes.GOLD_SPOKE,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](7);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.EURC,
        config: IHub.SpokeConfig({
          addCap: 300000,
          drawCap: 312500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 187500,
          drawCap: 50000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[2] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 200000,
          drawCap: 50000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[3] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.RLUSD,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 90000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[4] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDG,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 90000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[5] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.frxUSD,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 62500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[6] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 12500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[6] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: Spokes.FOREX_SPOKE,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](7);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 130,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WBTC,
        config: IHub.SpokeConfig({
          addCap: 6,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[2] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.cbBTC,
        config: IHub.SpokeConfig({
          addCap: 5,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[3] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.wstETH,
        config: IHub.SpokeConfig({
          addCap: 114,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[4] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 150000,
          drawCap: 175000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[5] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 150000,
          drawCap: 187500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[6] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 500000,
          drawCap: 562500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[7] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: Spokes.BLUECHIP_SPOKE,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](4);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 125000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.frxUSD,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 62500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[2] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.EURC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 50000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[3] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 125000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[8] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: Spokes.BLUECHIP_SPOKE,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](7);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_USDe,
        config: IHub.SpokeConfig({
          addCap: 6000000,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_sUSDe,
        config: IHub.SpokeConfig({
          addCap: 6000000,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[2] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.sUSDe,
        config: IHub.SpokeConfig({
          addCap: 375000,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[3] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDe,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 300000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[4] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 150000,
          drawCap: 187500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[5] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 150000,
          drawCap: 187500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[6] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 500000,
          drawCap: 562500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[9] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](3);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 125000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.frxUSD,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 62500,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[2] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 125000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[10] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](4);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_USDe,
        config: IHub.SpokeConfig({
          addCap: 6000000,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[1] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_sUSDe,
        config: IHub.SpokeConfig({
          addCap: 6000000,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[2] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.sUSDe,
        config: IHub.SpokeConfig({
          addCap: 250000,
          drawCap: 0,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      assets[3] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDe,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 325000,
          riskPremiumThreshold: 100000,
          active: true,
          halted: false
        })
      });
      additions[11] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: Spokes.ETHENA_CORRELATED_SPOKE,
        assets: assets
      });
    }
    return additions;
  }

  function spokeLiquidationConfigUpdates()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.LiquidationConfigUpdate[] memory updates)
  {
    updates = new IAaveV4ConfigEngine.LiquidationConfigUpdate[](10);
    updates[0] = IAaveV4ConfigEngine.LiquidationConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      targetHealthFactor: 1240000000000000000,
      healthFactorForMaxBonus: 900000000000000000,
      liquidationBonusFactor: 9000
    });
    updates[1] = IAaveV4ConfigEngine.LiquidationConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LIDO_ESPOKE,
      targetHealthFactor: 1013700000000000000,
      healthFactorForMaxBonus: 990000000000000000,
      liquidationBonusFactor: 10000
    });
    updates[2] = IAaveV4ConfigEngine.LiquidationConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHERFI_ESPOKE,
      targetHealthFactor: 1019100000000000000,
      healthFactorForMaxBonus: 990000000000000000,
      liquidationBonusFactor: 10000
    });
    updates[3] = IAaveV4ConfigEngine.LiquidationConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.KELP_ESPOKE,
      targetHealthFactor: 1021800000000000000,
      healthFactorForMaxBonus: 990000000000000000,
      liquidationBonusFactor: 10000
    });
    updates[4] = IAaveV4ConfigEngine.LiquidationConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      targetHealthFactor: 1061500000000000000,
      healthFactorForMaxBonus: 990000000000000000,
      liquidationBonusFactor: 10000
    });
    updates[5] = IAaveV4ConfigEngine.LiquidationConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      targetHealthFactor: 1307500000000000000,
      healthFactorForMaxBonus: 900000000000000000,
      liquidationBonusFactor: 9000
    });
    updates[6] = IAaveV4ConfigEngine.LiquidationConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      targetHealthFactor: 1044200000000000000,
      healthFactorForMaxBonus: 990000000000000000,
      liquidationBonusFactor: 10000
    });
    updates[7] = IAaveV4ConfigEngine.LiquidationConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      targetHealthFactor: 1174000000000000000,
      healthFactorForMaxBonus: 900000000000000000,
      liquidationBonusFactor: 9000
    });
    updates[8] = IAaveV4ConfigEngine.LiquidationConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      targetHealthFactor: 1033200000000000000,
      healthFactorForMaxBonus: 990000000000000000,
      liquidationBonusFactor: 10000
    });
    updates[9] = IAaveV4ConfigEngine.LiquidationConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      targetHealthFactor: 1027700000000000000,
      healthFactorForMaxBonus: 990000000000000000,
      liquidationBonusFactor: 10000
    });
    return updates;
  }
}
