// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {ISpokeConfigurator} from 'src/spoke/interfaces/ISpokeConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';
import {ISpoke} from 'src/spoke/interfaces/ISpoke.sol';
import {IAssetInterestRateStrategy} from 'src/hub/interfaces/IAssetInterestRateStrategy.sol';

import {Hubs, Spokes, Tokens, IrStrategies, Infra} from './AaveV4Contracts.sol';

contract ConfigPayload_1a_HubAssetListings is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function hubAssetListings()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.AssetListing[] memory listings)
  {
    listings = new IAaveV4ConfigEngine.AssetListing[](11);
    listings[0] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WETH,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1500,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 235,
        rateGrowthAfterOptimal: 1400
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 250,
        name: 'Tokenized Aave Core WETH',
        symbol: 'aCore-WETH'
      })
    });
    listings[1] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.wstETH,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Core wstETH',
        symbol: 'aCore-wstETH'
      })
    });
    listings[2] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.weETH,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Core weETH',
        symbol: 'aCore-weETH'
      })
    });
    listings[3] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.rsETH,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0,
        name: 'Tokenized Aave Core rsETH',
        symbol: 'aCore-rsETH'
      })
    });
    listings[4] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDT,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 2000
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 312500,
        name: 'Tokenized Aave Core USDT',
        symbol: 'aCore-USDT'
      })
    });
    listings[5] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDC,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 2000
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 312500,
        name: 'Tokenized Aave Core USDC',
        symbol: 'aCore-USDC'
      })
    });
    listings[6] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.GHO,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3000
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 125000,
        name: 'Tokenized Aave Core GHO',
        symbol: 'aCore-GHO'
      })
    });
    listings[7] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.RLUSD,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 8000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3500
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 125000,
        name: 'Tokenized Aave Core RLUSD',
        symbol: 'aCore-RLUSD'
      })
    });
    listings[8] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDG,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3500
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 125000,
        name: 'Tokenized Aave Core USDG',
        symbol: 'aCore-USDG'
      })
    });
    listings[9] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.frxUSD,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3500
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 125000,
        name: 'Tokenized Aave Core frxUSD',
        symbol: 'aCore-frxUSD'
      })
    });
    listings[10] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.EURC,
      decimals: 0,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 550,
        rateGrowthAfterOptimal: 3500
      }),
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 312500,
        name: 'Core Tokenized EURC',
        symbol: 'aCore-EURC'
      })
    });
    return listings;
  }
}
