// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {ISpokeConfigurator} from 'src/spoke/interfaces/ISpokeConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';
import {ISpoke} from 'src/spoke/interfaces/ISpoke.sol';
import {IAssetInterestRateStrategy} from 'src/hub/interfaces/IAssetInterestRateStrategy.sol';

import {Hubs, Spokes, Tokens, IrStrategies, Infra} from './AaveV4Contracts.sol';

contract ConfigPayload_3a_SpokeReserveListings is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function spokeReserveListings()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.ReserveListing[] memory listings)
  {
    listings = new IAaveV4ConfigEngine.ReserveListing[](30);
    listings[0] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WETH,
      priceSource: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 8300,
        maxLiquidationBonus: 10555,
        liquidationFee: 1000
      })
    });
    listings[1] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.wstETH,
      priceSource: 0x8B6851156023f4f5A66F68BEA80851c3D905Ac93,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 8000,
        maxLiquidationBonus: 10666,
        liquidationFee: 1000
      })
    });
    listings[2] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.weETH,
      priceSource: 0x87625393534d5C102cADB66D37201dF24cc26d4C,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 8000,
        maxLiquidationBonus: 10777,
        liquidationFee: 1000
      })
    });
    listings[3] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WBTC,
      priceSource: 0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 7800,
        maxLiquidationBonus: 10555,
        liquidationFee: 1000
      })
    });
    listings[4] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.cbBTC,
      priceSource: 0x2665701293fCbEB223D11A08D826563EDcCE423A,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 7800,
        maxLiquidationBonus: 10555,
        liquidationFee: 1000
      })
    });
    listings[5] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.AAVE,
      priceSource: 0xbd7F896e60B650C01caf2d7279a1148189A68884,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 7600,
        maxLiquidationBonus: 10833,
        liquidationFee: 1000
      })
    });
    listings[6] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.LINK,
      priceSource: 0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 7100,
        maxLiquidationBonus: 10777,
        liquidationFee: 1000
      })
    });
    listings[7] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDC,
      priceSource: 0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 7800,
        maxLiquidationBonus: 10500,
        liquidationFee: 1000
      })
    });
    listings[8] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDT,
      priceSource: 0x3E7d1eAB13ad0104d2750B8863b489D65364e32D,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 7800,
        maxLiquidationBonus: 10500,
        liquidationFee: 1000
      })
    });
    listings[9] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.EURC,
      priceSource: 0x04F84020Fdf10d9ee64D1dcC2986EDF2F556DA11,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[10] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.RLUSD,
      priceSource: 0x26C46B7aD0012cA71F2298ada567dC9Af14E7f2A,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[11] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDG,
      priceSource: 0x14f0737d6b705259e521EA6E9E3506AC78dBd311,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[12] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.frxUSD,
      priceSource: 0x9B4a96210bc8D9D55b1908B465D8B0de68B7fF83,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[13] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.GHO,
      priceSource: 0x3f12643D3f6f874d39C2a4c9f2Cd6f2DbAC877FC,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[14] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LIDO_ESPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.wstETH,
      priceSource: 0x8B6851156023f4f5A66F68BEA80851c3D905Ac93,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9550,
        maxLiquidationBonus: 10100,
        liquidationFee: 1000
      })
    });
    listings[15] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LIDO_ESPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WETH,
      priceSource: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[16] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHERFI_ESPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.weETH,
      priceSource: 0x87625393534d5C102cADB66D37201dF24cc26d4C,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9550,
        maxLiquidationBonus: 10100,
        liquidationFee: 1000
      })
    });
    listings[17] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHERFI_ESPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WETH,
      priceSource: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[18] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.KELP_ESPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.rsETH,
      priceSource: 0x7292C95A5f6A501a9c4B34f6393e221F2A0139c3,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9500,
        maxLiquidationBonus: 10100,
        liquidationFee: 1000
      })
    });
    listings[19] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.KELP_ESPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WETH,
      priceSource: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[20] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.LBTC,
      priceSource: 0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 8600,
        maxLiquidationBonus: 10300,
        liquidationFee: 1000
      })
    });
    listings[21] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WBTC,
      priceSource: 0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[22] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.cbBTC,
      priceSource: 0x2665701293fCbEB223D11A08D826563EDcCE423A,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[23] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.XAUt,
      priceSource: 0x214eD9Da11D2fbe465a6fc601a91E62EbEc1a0D6,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 7500,
        maxLiquidationBonus: 10666,
        liquidationFee: 1000
      })
    });
    listings[24] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDC,
      priceSource: 0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[25] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.RLUSD,
      priceSource: 0x26C46B7aD0012cA71F2298ada567dC9Af14E7f2A,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[26] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDG,
      priceSource: 0x14f0737d6b705259e521EA6E9E3506AC78dBd311,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[27] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.frxUSD,
      priceSource: 0x9B4a96210bc8D9D55b1908B465D8B0de68B7fF83,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[28] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.EURC,
      priceSource: 0x04F84020Fdf10d9ee64D1dcC2986EDF2F556DA11,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[29] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.GHO,
      priceSource: 0x3f12643D3f6f874d39C2a4c9f2Cd6f2DbAC877FC,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    return listings;
  }
}
