// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {Script} from 'forge-std/Script.sol';
import {TokenizationSpokeInstance} from 'src/spoke/instances/TokenizationSpokeInstance.sol';
import {TransparentUpgradeableProxy} from 'src/dependencies/openzeppelin/TransparentUpgradeableProxy.sol';
import {Hubs, Tokens} from './AaveV4Contracts.sol';

contract Factory {
  function create(
    address hub,
    address token,
    string memory name,
    string memory symbol,
    address proxyAdminOwner
  ) external returns (address) {
    address impl = address(new TokenizationSpokeInstance(hub, token));
    return
      address(
        new TransparentUpgradeableProxy(
          impl,
          proxyAdminOwner,
          abi.encodeCall(TokenizationSpokeInstance.initialize, (name, symbol))
        )
      );
  }
}

contract TokenizationSpokeDeploy is Script {
  function run() public {
    vm.startBroadcast();
    Factory factory = new Factory();
    (, address caller, ) = vm.readCallers();
    address proxy;

    // --- CORE_HUB ---
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.WETH,
      'Tokenized Aave Core WETH',
      'aCore-WETH',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'WETH', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.wstETH,
      'Tokenized Aave Core wstETH',
      'aCore-wstETH',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'wstETH', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.weETH,
      'Tokenized Aave Core weETH',
      'aCore-weETH',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'weETH', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.rsETH,
      'Tokenized Aave Core rsETH',
      'aCore-rsETH',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'rsETH', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.USDT,
      'Tokenized Aave Core USDT',
      'aCore-USDT',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'USDT', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.USDC,
      'Tokenized Aave Core USDC',
      'aCore-USDC',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'USDC', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.GHO,
      'Tokenized Aave Core GHO',
      'aCore-GHO',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'GHO', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.RLUSD,
      'Tokenized Aave Core RLUSD',
      'aCore-RLUSD',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'RLUSD', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.USDG,
      'Tokenized Aave Core USDG',
      'aCore-USDG',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'USDG', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.frxUSD,
      'Tokenized Aave Core frxUSD',
      'aCore-frxUSD',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'frxUSD', proxy);
    proxy = factory.create(Hubs.CORE_HUB, Tokens.EURC, 'Core Tokenized EURC', 'aCore-EURC', caller);
    vm.serializeAddress('CORE_HUB', 'EURC', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.WBTC,
      'Tokenized Aave Core WBTC',
      'aCore-WBTC',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'WBTC', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.cbBTC,
      'Tokenized Aave Core cbBTC',
      'aCore-cbBTC',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'cbBTC', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.LBTC,
      'Tokenized Aave Core LBTC',
      'aCore-LBTC',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'LBTC', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.XAUt,
      'Tokenized Aave Core XAUt',
      'aCore-XAUt',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'XAUt', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.AAVE,
      'Tokenized Aave Core AAVE',
      'aCore-AAVE',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'AAVE', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.LINK,
      'Tokenized Aave Core LINK',
      'aCore-LINK',
      caller
    );
    string memory core_hubJson = vm.serializeAddress('CORE_HUB', 'LINK', proxy);

    // --- PRIME_HUB ---
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.WETH,
      'Tokenized Aave Prime WETH',
      'aPrime-WETH',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'WETH', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.WBTC,
      'Tokenized Aave Prime WBTC',
      'aPrime-WBTC',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'WBTC', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.cbBTC,
      'Tokenized Aave Prime cbBTC',
      'aPrime-cbBTC',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'cbBTC', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.wstETH,
      'Tokenized Aave Prime wstETH',
      'aPrime-wstETH',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'wstETH', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.USDC,
      'Tokenized Aave Prime USDC',
      'aPrime-USDC',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'USDC', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.USDT,
      'Tokenized Aave Prime USDT',
      'aPrime-USDT',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'USDT', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.GHO,
      'Tokenized Aave Prime GHO',
      'aPrime-GHO',
      caller
    );
    string memory prime_hubJson = vm.serializeAddress('PRIME_HUB', 'GHO', proxy);

    // --- PLUS_HUB ---
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.PT_sUSDe,
      'Tokenized Aave Plus PT_sUSDe',
      'aPlus-PT_sUSDe',
      caller
    );
    vm.serializeAddress('PLUS_HUB', 'PT_sUSDe', proxy);
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.PT_USDe,
      'Tokenized Aave Plus PT_USDe',
      'aPlus-PT_USDe',
      caller
    );
    vm.serializeAddress('PLUS_HUB', 'PT_USDe', proxy);
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.sUSDe,
      'Tokenized Aave Plus sUSDe',
      'aPlus-sUSDe',
      caller
    );
    vm.serializeAddress('PLUS_HUB', 'sUSDe', proxy);
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.USDe,
      'Tokenized Aave Plus USDe',
      'aPlus-USDe',
      caller
    );
    vm.serializeAddress('PLUS_HUB', 'USDe', proxy);
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.USDC,
      'Tokenized Aave Plus USDC',
      'aPlus-USDC',
      caller
    );
    vm.serializeAddress('PLUS_HUB', 'USDC', proxy);
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.GHO,
      'Tokenized Aave Plus GHO',
      'aPlus-GHO',
      caller
    );
    vm.serializeAddress('PLUS_HUB', 'GHO', proxy);
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.USDT,
      'Tokenized Aave Plus USDT',
      'aPlus-USDT',
      caller
    );
    string memory plus_hubJson = vm.serializeAddress('PLUS_HUB', 'USDT', proxy);

    vm.stopBroadcast();

    vm.serializeString('root', 'CORE_HUB', core_hubJson);
    vm.serializeString('root', 'PRIME_HUB', prime_hubJson);
    string memory finalJson = vm.serializeString('root', 'PLUS_HUB', plus_hubJson);
    vm.writeJson(finalJson, 'scripts/config/tokenization-deploy.json');
  }
}
