// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';

import {Hubs, Tokens, Infra} from './AaveV4Contracts.sol';

contract TokenizationSpokePayload is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function hubSpokeToAssetsAdditions()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.SpokeToAssetsAddition[] memory additions)
  {
    additions = new IAaveV4ConfigEngine.SpokeToAssetsAddition[](31);
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 250,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[0] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xaA05aeCb8033BDD7a442022B229CFC0AF24Ee333,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.wstETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[1] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x9C619D6a9b30e70fd85b7A694C1C07Ba16B523FF,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.weETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[2] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xECdF0599E74E6514Cc5Cd77e9cE8c7907a17C0d8,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.rsETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[3] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x169ecd1301DE2330752881AF8a046aA85463a560,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[4] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xB7f8343D8ed739d9BF18d71b497744cfa805dc59,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[5] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xd9a2b611eF2Ae3E6eb3281e2eBd321be4118A3D4,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[6] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x6dEFf40f794d9036DCd01D5bcEDAe43Af90A0408,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.RLUSD,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[7] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x8d595DEd7bBcE2452468ca48649825b8df31db4b,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDG,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[8] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xA7C750Ea88A0b7F871d7a24f34a5cFf29EDF7F3B,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.frxUSD,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[9] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xb30377c1f0AA25D8d761D480A3Ae283941e85D0c,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.EURC,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[10] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x137dcF9E2FC4822FD3E8a182141cC81F470E7DBa,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[11] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x010bf12D04156018644a27bF218B6b5ae3F6296d,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.cbBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[12] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xB05a14556C620A5dDD3ffe80948B9bF764252a3B,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.LBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[13] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x5aCFA6Dd968a462fb3563ff1f94a3238F172Df55,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.XAUt,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[14] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x1F1bC61dC54d5DFCb636aFb06CCc7eE8Fd8f98f7,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.AAVE,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[15] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x47925a55538d0369bDA47fcf16fe410EcF379523,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.LINK,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[16] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xcF32fcC807A37F00fB01435c0e56F2d31Ad041DB,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[17] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x40A036B03ea93870f8cd57b574Ecee615756B406,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[18] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x5fFeCC96cdC489a13B9E5c3f313e04e80EbAAD0D,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.cbBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[19] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xAf7b4785AA3697ca947bBD1cc77512bE76E7175F,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.wstETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[20] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xc6386A14fAB16e39136001601509c10ECFEb2713,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[21] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x1593908058a4319ab70396D7E83Da5A217249C8E,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[22] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xd22Df1Cf9A4D8C0cB6980d0E61d177e1A9E5237c,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[23] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x83d18238A6EA2Bd2662ff0d0114CBC9A4534cb0E,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_sUSDe,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[24] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x6857559D4a0E56Eb13230E83aa74db0bc0c9B98C,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_USDe,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[25] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x5609aCAa4dA5c371Be0CC36F15DdCB152053d237,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.sUSDe,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[26] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0xD0D6fDf53980C76Ff3C3Fc79BD380324De43B864,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDe,
        config: IHub.SpokeConfig({
          addCap: 78000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[27] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0xf600CF3dda692B916B29fc735a5073B4D24F61c1,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[28] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x61c13aaD32201b963e29c486dc77114D44AE41d6,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[29] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x8BB75dA903239D00b07af64C4f3d3a7b89AE0659,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[30] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x74a8E6F004A735d14fCe759b7ca7A46b99f34306,
        assets: assets
      });
    }
    return additions;
  }
}
