// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';

import {Hubs, Tokens, Infra} from './AaveV4Contracts.sol';

contract TokenizationSpokePayload is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function hubSpokeToAssetsAdditions()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.SpokeToAssetsAddition[] memory additions)
  {
    additions = new IAaveV4ConfigEngine.SpokeToAssetsAddition[](31);
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 250,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[0] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x1EB64656C34f861551d2891C759B53B3C3c0e6E3,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.wstETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[1] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x761134A6F67761acdf8adF9D63cA4a1Db2C78ab5,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.weETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[2] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xf31463c150b3bE682d96f5695BE94D0C1C611F85,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.rsETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[3] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x8230B1F89b4D49445fe666343d6f0A4f164D4C8A,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[4] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x0722337BDb61540A36968be51DC417eCE05223FF,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[5] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x026fE4994aA8e8730C355Ce7717f8BeCEdEE4DEc,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[6] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xBF0Bb6C65D98A6C6F0A1F95dB753dF1D58bc515e,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.RLUSD,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[7] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xB87F066E22Ea07bB937EA1B1168bd83FA399d0F4,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDG,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[8] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xD067E9b23f399a9E00129ff2aCd5B0041E15Cdd0,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.frxUSD,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[9] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xd17834CdC03796596B544e9Bc48d7531bD342142,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.EURC,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[10] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xEcd90c45eB983ed1D700Db4E2f7e2b14ACa182b0,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[11] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x9fF81124B6d11b24F0718d6b946fa43Fef6Ab631,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.cbBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[12] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x76901541F5dCEbCCdf4D7E939Ff981983C5a2D17,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.LBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[13] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xEa369D6C765CE9082aAA6604147F479b5063c5A2,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.XAUt,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[14] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x55C9B8b9644F2CAe01837858076CBF88c5c9d8F3,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.AAVE,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[15] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x6CFeB86CeDe9e9046F8494b7740e33C2e84476b5,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.LINK,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[16] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x87fF377FE50E4CF85Eab04430851F121a8E5c4b5,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[17] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xbbd43F745dE3Ddf5011aBC83A80B1f1340889f4e,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[18] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xe117DE80bAa8A3a66b29353122491D3006faEfeF,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.cbBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[19] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x33aAEBFDfaBfDeC769bd3e844e86e05Fd6A42447,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.wstETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[20] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xE7038EF94Ca641c7cAcCf42bD8f8A6AF98736959,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[21] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x91f5D93974a2C043B242F358e318546fAF47a8e8,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[22] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xe21ab93fE703741e650d746ACA583C2F7686DabD,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[23] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xFf797a0E186e1a761c77cD1fE1b209110d682f25,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_sUSDe,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[24] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x68b54C6724CA2A253AD3E193FCA4262cA070F332,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_USDe,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[25] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x97089631BEd7d7f1c450192860980B9f2437126a,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.sUSDe,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[26] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x80f8423E9675195E9344Df4D84E05Fb2742558f7,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDe,
        config: IHub.SpokeConfig({
          addCap: 78000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[27] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x2A5e259a740C943035eC17D6e5fB85000A47D614,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[28] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x6CC92a311582395C4Bc27BB5e7CbBbB4B474C380,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[29] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0xc90d0D28418e2a912a9633aAd93606597ce8A3F5,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[30] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x14E39e6b7A248B06522b52963D1E41Aeb9CD5Fc9,
        assets: assets
      });
    }
    return additions;
  }
}
