// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {ISpokeConfigurator} from 'src/spoke/interfaces/ISpokeConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';
import {ISpoke} from 'src/spoke/interfaces/ISpoke.sol';
import {IAssetInterestRateStrategy} from 'src/hub/interfaces/IAssetInterestRateStrategy.sol';

import {Hubs, Spokes, Tokens, IrStrategies, Infra} from 'scripts/payload/AaveV4Contracts.sol';

contract ConfigPayload_1_HubAssetListings is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function hubAssetListings()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.AssetListing[] memory listings)
  {
    listings = new IAaveV4ConfigEngine.AssetListing[](31);
    listings[0] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1500,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 235,
        rateGrowthAfterOptimal: 1400
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 250
        name: '', // actual: "Wrapped Aave Core WETH"
        symbol: '' // actual: "waCoreWETH"
      })
    });
    listings[1] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.wstETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Core wstETH"
        symbol: '' // actual: "waCorewstETH"
      })
    });
    listings[2] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.weETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Core weETH"
        symbol: '' // actual: "waCoreweETH"
      })
    });
    listings[3] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.rsETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Core rsETH"
        symbol: '' // actual: "waCorersETH"
      })
    });
    listings[4] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDT,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 312500
        name: '', // actual: "Wrapped Aave Core USDT"
        symbol: '' // actual: "waCoreUSDT"
      })
    });
    listings[5] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 312500
        name: '', // actual: "Wrapped Aave Core USDC"
        symbol: '' // actual: "waCoreUSDC"
      })
    });
    listings[6] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.GHO,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Wrapped Aave Core GHO"
        symbol: '' // actual: "waCoreGHO"
      })
    });
    listings[7] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.RLUSD,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 8000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3500
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Wrapped Aave Core RLUSD"
        symbol: '' // actual: "waCoreRLUSD"
      })
    });
    listings[8] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDG,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3500
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Wrapped Aave Core USDG"
        symbol: '' // actual: "waCoreUSDG"
      })
    });
    listings[9] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.frxUSD,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3500
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Wrapped Aave Core frxUSD"
        symbol: '' // actual: "waCorefrxUSD"
      })
    });
    listings[10] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.EURC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 550,
        rateGrowthAfterOptimal: 3500
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 112500
        name: '', // actual: "Wrapped Aave Core EURC"
        symbol: '' // actual: "waCoreEURC"
      })
    });
    listings[11] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WBTC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 8000,
        baseDrawnRate: 25,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 6000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Core WBTC"
        symbol: '' // actual: "waCoreWBTC"
      })
    });
    listings[12] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.cbBTC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 8000,
        baseDrawnRate: 25,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 6000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Core cbBTC"
        symbol: '' // actual: "waCorecbBTC"
      })
    });
    listings[13] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.LBTC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Core LBTC"
        symbol: '' // actual: "waCoreLBTC"
      })
    });
    listings[14] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.XAUt,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Core XAUt"
        symbol: '' // actual: "waCoreXAUt"
      })
    });
    listings[15] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.AAVE,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Core AAVE"
        symbol: '' // actual: "waCoreAAVE"
      })
    });
    listings[16] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.LINK,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Core LINK"
        symbol: '' // actual: "waCoreLINK"
      })
    });
    listings[17] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.WETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Prime WETH"
        symbol: '' // actual: "waPrimeWETH"
      })
    });
    listings[18] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.WBTC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Prime WBTC"
        symbol: '' // actual: "waPrimeWBTC"
      })
    });
    listings[19] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.cbBTC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Prime cbBTC"
        symbol: '' // actual: "waPrimecbBTC"
      })
    });
    listings[20] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.wstETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Prime wstETH"
        symbol: '' // actual: "waPrimewstETH"
      })
    });
    listings[21] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.USDC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 37500
        name: '', // actual: "Wrapped Aave Prime USDC"
        symbol: '' // actual: "waPrimeUSDC"
      })
    });
    listings[22] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.USDT,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 37500
        name: '', // actual: "Wrapped Aave Prime USDT"
        symbol: '' // actual: "waPrimeUSDT"
      })
    });
    listings[23] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.GHO,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Wrapped Aave Prime GHO"
        symbol: '' // actual: "waPrimeGHO"
      })
    });
    listings[24] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.PT_sUSDE_7MAY2026,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Plus PT_sUSDE_7MAY2026"
        symbol: '' // actual: "aPlus-PT_sUSDE_7MAY2026"
      })
    });
    listings[25] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.PT_USDE_7MAY2026,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Plus PT_USDE_7MAY2026"
        symbol: '' // actual: "aPlus-PT_USDE_7MAY2026"
      })
    });
    listings[26] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.sUSDe,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 0,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Wrapped Aave Plus sUSDe"
        symbol: '' // actual: "waPlussUSDe"
      })
    });
    listings[27] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.USDe,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2500,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 450,
        rateGrowthAfterOptimal: 3000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 78000
        name: '', // actual: "Wrapped Aave Plus USDe"
        symbol: '' // actual: "waPlusUSDe"
      })
    });
    listings[28] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.USDC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1500,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 450,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 37500
        name: '', // actual: "Wrapped Aave Plus USDC"
        symbol: '' // actual: "waPlusUSDC"
      })
    });
    listings[29] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.GHO,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 450,
        rateGrowthAfterOptimal: 3000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Wrapped Aave Plus GHO"
        symbol: '' // actual: "waPlusGHO"
      })
    });
    listings[30] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.USDT,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1500,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 450,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 37500
        name: '', // actual: "Wrapped Aave Plus USDT"
        symbol: '' // actual: "waPlusUSDT"
      })
    });
    return listings;
  }
}
