// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {ISpokeConfigurator} from 'src/spoke/interfaces/ISpokeConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';
import {ISpoke} from 'src/spoke/interfaces/ISpoke.sol';
import {IAssetInterestRateStrategy} from 'src/hub/interfaces/IAssetInterestRateStrategy.sol';

import {Hubs, Spokes, Tokens, IrStrategies, Infra} from 'scripts/payload/AaveV4Contracts.sol';

contract ConfigPayload_1_HubAssetListings is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function hubAssetListings()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.AssetListing[] memory listings)
  {
    listings = new IAaveV4ConfigEngine.AssetListing[](31);
    listings[0] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1500,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 235,
        rateGrowthAfterOptimal: 1400
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 250
        name: '', // actual: "Tokenized Aave Core WETH"
        symbol: '' // actual: "aCore-WETH"
      })
    });
    listings[1] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.wstETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Core wstETH"
        symbol: '' // actual: "aCore-wstETH"
      })
    });
    listings[2] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.weETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Core weETH"
        symbol: '' // actual: "aCore-weETH"
      })
    });
    listings[3] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.rsETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Core rsETH"
        symbol: '' // actual: "aCore-rsETH"
      })
    });
    listings[4] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDT,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 312500
        name: '', // actual: "Tokenized Aave Core USDT"
        symbol: '' // actual: "aCore-USDT"
      })
    });
    listings[5] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 312500
        name: '', // actual: "Tokenized Aave Core USDC"
        symbol: '' // actual: "aCore-USDC"
      })
    });
    listings[6] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.GHO,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Tokenized Aave Core GHO"
        symbol: '' // actual: "aCore-GHO"
      })
    });
    listings[7] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.RLUSD,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 8000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3500
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Tokenized Aave Core RLUSD"
        symbol: '' // actual: "aCore-RLUSD"
      })
    });
    listings[8] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDG,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3500
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Tokenized Aave Core USDG"
        symbol: '' // actual: "aCore-USDG"
      })
    });
    listings[9] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.frxUSD,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3500
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Tokenized Aave Core frxUSD"
        symbol: '' // actual: "aCore-frxUSD"
      })
    });
    listings[10] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.EURC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 550,
        rateGrowthAfterOptimal: 3500
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 112500
        name: '', // actual: "Tokenized Aave Core EURC"
        symbol: '' // actual: "aCore-EURC"
      })
    });
    listings[11] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.WBTC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 8000,
        baseDrawnRate: 25,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 6000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Core WBTC"
        symbol: '' // actual: "aCore-WBTC"
      })
    });
    listings[12] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.cbBTC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 8000,
        baseDrawnRate: 25,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 6000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Core cbBTC"
        symbol: '' // actual: "aCore-cbBTC"
      })
    });
    listings[13] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.LBTC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Core LBTC"
        symbol: '' // actual: "aCore-LBTC"
      })
    });
    listings[14] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.XAUt,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Core XAUt"
        symbol: '' // actual: "aCore-XAUt"
      })
    });
    listings[15] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.AAVE,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Core AAVE"
        symbol: '' // actual: "aCore-AAVE"
      })
    });
    listings[16] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.CORE_HUB,
      underlying: Tokens.LINK,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.CORE_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Core LINK"
        symbol: '' // actual: "aCore-LINK"
      })
    });
    listings[17] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.WETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Prime WETH"
        symbol: '' // actual: "aPrime-WETH"
      })
    });
    listings[18] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.WBTC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Prime WBTC"
        symbol: '' // actual: "aPrime-WBTC"
      })
    });
    listings[19] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.cbBTC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Prime cbBTC"
        symbol: '' // actual: "aPrime-cbBTC"
      })
    });
    listings[20] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.wstETH,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Prime wstETH"
        symbol: '' // actual: "aPrime-wstETH"
      })
    });
    listings[21] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.USDC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 37500
        name: '', // actual: "Tokenized Aave Prime USDC"
        symbol: '' // actual: "aPrime-USDC"
      })
    });
    listings[22] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.USDT,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 37500
        name: '', // actual: "Tokenized Aave Prime USDT"
        symbol: '' // actual: "aPrime-USDT"
      })
    });
    listings[23] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.GHO,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PRIME_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 400,
        rateGrowthAfterOptimal: 3000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Tokenized Aave Prime GHO"
        symbol: '' // actual: "aPrime-GHO"
      })
    });
    listings[24] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.PT_sUSDE_7MAY2026,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Plus PT_sUSDE_7MAY2026"
        symbol: '' // actual: "aPlus-PT_sUSDE_7MAY2026"
      })
    });
    listings[25] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.PT_USDE_7MAY2026,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Plus PT_USDE_7MAY2026"
        symbol: '' // actual: "aPlus-PT_USDE_7MAY2026"
      })
    });
    listings[26] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.sUSDe,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9900,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 0,
        rateGrowthAfterOptimal: 0
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 0
        name: '', // actual: "Tokenized Aave Plus sUSDe"
        symbol: '' // actual: "aPlus-sUSDe"
      })
    });
    listings[27] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.USDe,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 2500,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 450,
        rateGrowthAfterOptimal: 3000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 78000
        name: '', // actual: "Tokenized Aave Plus USDe"
        symbol: '' // actual: "aPlus-USDe"
      })
    });
    listings[28] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.USDC,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1500,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 450,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 37500
        name: '', // actual: "Tokenized Aave Plus USDC"
        symbol: '' // actual: "aPlus-USDC"
      })
    });
    listings[29] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.GHO,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1000,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9000,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 450,
        rateGrowthAfterOptimal: 3000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 125000
        name: '', // actual: "Tokenized Aave Plus GHO"
        symbol: '' // actual: "aPlus-GHO"
      })
    });
    listings[30] = IAaveV4ConfigEngine.AssetListing({
      hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.USDT,
      feeReceiver: Infra.TREASURY_SPOKE,
      liquidityFee: 1500,
      irStrategy: IrStrategies.PLUS_HUB,
      irData: IAssetInterestRateStrategy.InterestRateData({
        optimalUsageRatio: 9200,
        baseDrawnRate: 0,
        rateGrowthBeforeOptimal: 450,
        rateGrowthAfterOptimal: 2000
      }),
      // Tokenization is being skipped
      tokenization: IAaveV4ConfigEngine.TokenizationSpokeConfig({
        addCap: 0, // actual: 37500
        name: '', // actual: "Tokenized Aave Plus USDT"
        symbol: '' // actual: "aPlus-USDT"
      })
    });
    return listings;
  }
}
