// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {ISpokeConfigurator} from 'src/spoke/interfaces/ISpokeConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';
import {ISpoke} from 'src/spoke/interfaces/ISpoke.sol';
import {IAssetInterestRateStrategy} from 'src/hub/interfaces/IAssetInterestRateStrategy.sol';

import {Hubs, Spokes, Tokens, IrStrategies, Infra} from 'scripts/payload/AaveV4Contracts.sol';

contract ConfigPayload_5_PositionManagerSpokeRegistrations is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function positionManagerSpokeRegistrations()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.SpokeRegistration[] memory registrations)
  {
    registrations = new IAaveV4ConfigEngine.SpokeRegistration[](50);
    registrations[0] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      spoke: Spokes.MAIN_SPOKE,
      registered: true
    });
    registrations[1] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.GIVER_POSITION_MANAGER,
      spoke: Spokes.MAIN_SPOKE,
      registered: true
    });
    registrations[2] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.TAKER_POSITION_MANAGER,
      spoke: Spokes.MAIN_SPOKE,
      registered: true
    });
    registrations[3] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.SIGNATURE_GATEWAY,
      spoke: Spokes.MAIN_SPOKE,
      registered: true
    });
    registrations[4] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      spoke: Spokes.MAIN_SPOKE,
      registered: true
    });
    registrations[5] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      spoke: Spokes.LIDO_ESPOKE,
      registered: true
    });
    registrations[6] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.GIVER_POSITION_MANAGER,
      spoke: Spokes.LIDO_ESPOKE,
      registered: true
    });
    registrations[7] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.TAKER_POSITION_MANAGER,
      spoke: Spokes.LIDO_ESPOKE,
      registered: true
    });
    registrations[8] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.SIGNATURE_GATEWAY,
      spoke: Spokes.LIDO_ESPOKE,
      registered: true
    });
    registrations[9] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      spoke: Spokes.LIDO_ESPOKE,
      registered: true
    });
    registrations[10] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      spoke: Spokes.ETHERFI_ESPOKE,
      registered: true
    });
    registrations[11] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.GIVER_POSITION_MANAGER,
      spoke: Spokes.ETHERFI_ESPOKE,
      registered: true
    });
    registrations[12] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.TAKER_POSITION_MANAGER,
      spoke: Spokes.ETHERFI_ESPOKE,
      registered: true
    });
    registrations[13] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.SIGNATURE_GATEWAY,
      spoke: Spokes.ETHERFI_ESPOKE,
      registered: true
    });
    registrations[14] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      spoke: Spokes.ETHERFI_ESPOKE,
      registered: true
    });
    registrations[15] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      spoke: Spokes.KELP_ESPOKE,
      registered: true
    });
    registrations[16] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.GIVER_POSITION_MANAGER,
      spoke: Spokes.KELP_ESPOKE,
      registered: true
    });
    registrations[17] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.TAKER_POSITION_MANAGER,
      spoke: Spokes.KELP_ESPOKE,
      registered: true
    });
    registrations[18] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.SIGNATURE_GATEWAY,
      spoke: Spokes.KELP_ESPOKE,
      registered: true
    });
    registrations[19] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      spoke: Spokes.KELP_ESPOKE,
      registered: true
    });
    registrations[20] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      registered: true
    });
    registrations[21] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.GIVER_POSITION_MANAGER,
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      registered: true
    });
    registrations[22] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.TAKER_POSITION_MANAGER,
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      registered: true
    });
    registrations[23] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.SIGNATURE_GATEWAY,
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      registered: true
    });
    registrations[24] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      registered: true
    });
    registrations[25] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      spoke: Spokes.GOLD_SPOKE,
      registered: true
    });
    registrations[26] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.GIVER_POSITION_MANAGER,
      spoke: Spokes.GOLD_SPOKE,
      registered: true
    });
    registrations[27] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.TAKER_POSITION_MANAGER,
      spoke: Spokes.GOLD_SPOKE,
      registered: true
    });
    registrations[28] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.SIGNATURE_GATEWAY,
      spoke: Spokes.GOLD_SPOKE,
      registered: true
    });
    registrations[29] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      spoke: Spokes.GOLD_SPOKE,
      registered: true
    });
    registrations[30] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      spoke: Spokes.FOREX_SPOKE,
      registered: true
    });
    registrations[31] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.GIVER_POSITION_MANAGER,
      spoke: Spokes.FOREX_SPOKE,
      registered: true
    });
    registrations[32] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.TAKER_POSITION_MANAGER,
      spoke: Spokes.FOREX_SPOKE,
      registered: true
    });
    registrations[33] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.SIGNATURE_GATEWAY,
      spoke: Spokes.FOREX_SPOKE,
      registered: true
    });
    registrations[34] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      spoke: Spokes.FOREX_SPOKE,
      registered: true
    });
    registrations[35] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      spoke: Spokes.BLUECHIP_SPOKE,
      registered: true
    });
    registrations[36] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.GIVER_POSITION_MANAGER,
      spoke: Spokes.BLUECHIP_SPOKE,
      registered: true
    });
    registrations[37] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.TAKER_POSITION_MANAGER,
      spoke: Spokes.BLUECHIP_SPOKE,
      registered: true
    });
    registrations[38] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.SIGNATURE_GATEWAY,
      spoke: Spokes.BLUECHIP_SPOKE,
      registered: true
    });
    registrations[39] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      spoke: Spokes.BLUECHIP_SPOKE,
      registered: true
    });
    registrations[40] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      registered: true
    });
    registrations[41] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.GIVER_POSITION_MANAGER,
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      registered: true
    });
    registrations[42] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.TAKER_POSITION_MANAGER,
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      registered: true
    });
    registrations[43] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.SIGNATURE_GATEWAY,
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      registered: true
    });
    registrations[44] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      registered: true
    });
    registrations[45] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.CONFIG_POSITION_MANAGER,
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      registered: true
    });
    registrations[46] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.GIVER_POSITION_MANAGER,
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      registered: true
    });
    registrations[47] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.TAKER_POSITION_MANAGER,
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      registered: true
    });
    registrations[48] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.SIGNATURE_GATEWAY,
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      registered: true
    });
    registrations[49] = IAaveV4ConfigEngine.SpokeRegistration({
      positionManager: Infra.NATIVE_TOKEN_GATEWAY,
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      registered: true
    });
    return registrations;
  }
}
