// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {ISpokeConfigurator} from 'src/spoke/interfaces/ISpokeConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';
import {ISpoke} from 'src/spoke/interfaces/ISpoke.sol';
import {IAssetInterestRateStrategy} from 'src/hub/interfaces/IAssetInterestRateStrategy.sol';

import {Hubs, Spokes, Tokens, IrStrategies, Infra} from 'scripts/payload/AaveV4Contracts.sol';

contract ConfigPayload_3b_SpokeReserveListings is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function spokeReserveListings()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.ReserveListing[] memory listings)
  {
    listings = new IAaveV4ConfigEngine.ReserveListing[](33);
    listings[0] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDT,
      priceSource: 0x260326c220E469358846b187eE53328303Efe19C,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[1] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.EURC,
      priceSource: 0x04F84020Fdf10d9ee64D1dcC2986EDF2F556DA11,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9000,
        maxLiquidationBonus: 10200,
        liquidationFee: 1000
      })
    });
    listings[2] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDC,
      priceSource: 0x581b8Bc9d6104F71ad6da1f483B67500968C5994,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9000,
        maxLiquidationBonus: 10200,
        liquidationFee: 1000
      })
    });
    listings[3] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDT,
      priceSource: 0x260326c220E469358846b187eE53328303Efe19C,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9000,
        maxLiquidationBonus: 10200,
        liquidationFee: 1000
      })
    });
    listings[4] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.RLUSD,
      priceSource: 0xf0eaC18E908B34770FDEe46d069c846bDa866759,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[5] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDG,
      priceSource: 0x14f0737d6b705259e521EA6E9E3506AC78dBd311,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[6] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.frxUSD,
      priceSource: 0x25DEd2f9aE6ae9416693AB63Abe3aB25493861FD,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[7] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.GHO,
      priceSource: 0xD110cac5d8682A3b045D5524a9903E031d70FCCd,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[8] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.WETH,
      priceSource: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 8600,
        maxLiquidationBonus: 10444,
        liquidationFee: 1000
      })
    });
    listings[9] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.WBTC,
      priceSource: 0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 8450,
        maxLiquidationBonus: 10444,
        liquidationFee: 1000
      })
    });
    listings[10] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.cbBTC,
      priceSource: 0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 8450,
        maxLiquidationBonus: 10444,
        liquidationFee: 1000
      })
    });
    listings[11] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.wstETH,
      priceSource: 0x869C9Ae2C8fbe82a8b0F768b9F791f89E083222C,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 8550,
        maxLiquidationBonus: 10444,
        liquidationFee: 1000
      })
    });
    listings[12] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.USDC,
      priceSource: 0x581b8Bc9d6104F71ad6da1f483B67500968C5994,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[13] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.USDT,
      priceSource: 0x260326c220E469358846b187eE53328303Efe19C,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[14] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.GHO,
      priceSource: 0xD110cac5d8682A3b045D5524a9903E031d70FCCd,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[15] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDC,
      priceSource: 0x581b8Bc9d6104F71ad6da1f483B67500968C5994,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[16] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.frxUSD,
      priceSource: 0x25DEd2f9aE6ae9416693AB63Abe3aB25493861FD,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[17] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.EURC,
      priceSource: 0x04F84020Fdf10d9ee64D1dcC2986EDF2F556DA11,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[18] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDT,
      priceSource: 0x260326c220E469358846b187eE53328303Efe19C,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[19] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.PT_USDE_7MAY2026,
      priceSource: 0x0a72df02CE3E4185b6CEDf561f0AE651E9BeE235,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9300,
        maxLiquidationBonus: 10300,
        liquidationFee: 1000
      })
    });
    listings[20] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.PT_sUSDE_7MAY2026,
      priceSource: 0xa0dc0249c32fa79e8B9b17c735908a60b1141B40,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9200,
        maxLiquidationBonus: 10400,
        liquidationFee: 1000
      })
    });
    listings[21] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.sUSDe,
      priceSource: 0x42bc86f2f08419280a99d8fbEa4672e7c30a86ec,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9200,
        maxLiquidationBonus: 10300,
        liquidationFee: 1000
      })
    });
    listings[22] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.USDe,
      priceSource: 0xC26D4a1c46d884cfF6dE9800B6aE7A8Cf48B4Ff8,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9300,
        maxLiquidationBonus: 10200,
        liquidationFee: 1000
      })
    });
    listings[23] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.USDC,
      priceSource: 0x581b8Bc9d6104F71ad6da1f483B67500968C5994,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[24] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.USDT,
      priceSource: 0x260326c220E469358846b187eE53328303Efe19C,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[25] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.GHO,
      priceSource: 0xD110cac5d8682A3b045D5524a9903E031d70FCCd,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[26] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDC,
      priceSource: 0x581b8Bc9d6104F71ad6da1f483B67500968C5994,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[27] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.frxUSD,
      priceSource: 0x25DEd2f9aE6ae9416693AB63Abe3aB25493861FD,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[28] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_ECOSYSTEM_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDT,
      priceSource: 0x260326c220E469358846b187eE53328303Efe19C,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 0,
        maxLiquidationBonus: 10000,
        liquidationFee: 0
      })
    });
    listings[29] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.PT_USDE_7MAY2026,
      priceSource: 0x0a72df02CE3E4185b6CEDf561f0AE651E9BeE235,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9580,
        maxLiquidationBonus: 10200,
        liquidationFee: 1000
      })
    });
    listings[30] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.PT_sUSDE_7MAY2026,
      priceSource: 0xa0dc0249c32fa79e8B9b17c735908a60b1141B40,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9400,
        maxLiquidationBonus: 10300,
        liquidationFee: 1000
      })
    });
    listings[31] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.sUSDe,
      priceSource: 0x42bc86f2f08419280a99d8fbEa4672e7c30a86ec,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: false,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9200,
        maxLiquidationBonus: 10300,
        liquidationFee: 1000
      })
    });
    listings[32] = IAaveV4ConfigEngine.ReserveListing({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.ETHENA_CORRELATED_SPOKE,
      hub: Hubs.PLUS_HUB,
      underlying: Tokens.USDe,
      priceSource: 0xC26D4a1c46d884cfF6dE9800B6aE7A8Cf48B4Ff8,
      config: ISpoke.ReserveConfig({
        collateralRisk: 0,
        paused: false,
        frozen: false,
        borrowable: true,
        receiveSharesEnabled: true
      }),
      dynamicConfig: ISpoke.DynamicReserveConfig({
        collateralFactor: 9300,
        maxLiquidationBonus: 10200,
        liquidationFee: 1000
      })
    });
    return listings;
  }
}
