// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED by generateDiffPayload.ts — DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {EngineFlags} from 'src/config-engine/libraries/EngineFlags.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {ISpokeConfigurator} from 'src/spoke/interfaces/ISpokeConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';
import {ISpoke} from 'src/spoke/interfaces/ISpoke.sol';
import {IAssetInterestRateStrategy} from 'src/hub/interfaces/IAssetInterestRateStrategy.sol';

import {Hubs, Spokes, Tokens, IrStrategies, Infra} from 'scripts/payload/AaveV4Contracts.sol';

contract DiffPayload is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function spokeReserveConfigUpdates()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.ReserveConfigUpdate[] memory updates)
  {
    updates = new IAaveV4ConfigEngine.ReserveConfigUpdate[](4);
    updates[0] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.wstETH,
      priceSource: 0xe1D97bF61901B075E9626c8A2340a7De385861Ef,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    updates[1] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.AAVE,
      priceSource: 0x547a514d5e3769680Ce22B2361c10Ea13619e8a9,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    updates[2] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LIDO_ESPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.wstETH,
      priceSource: 0xe1D97bF61901B075E9626c8A2340a7De385861Ef,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    updates[3] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.PRIME_HUB,
      underlying: Tokens.wstETH,
      priceSource: 0xe1D97bF61901B075E9626c8A2340a7De385861Ef,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    return updates;
  }
}
