// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED by generateDiffPayload.ts — DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {EngineFlags} from 'src/config-engine/libraries/EngineFlags.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {ISpokeConfigurator} from 'src/spoke/interfaces/ISpokeConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';
import {ISpoke} from 'src/spoke/interfaces/ISpoke.sol';
import {IAssetInterestRateStrategy} from 'src/hub/interfaces/IAssetInterestRateStrategy.sol';

import {Hubs, Spokes, Tokens, IrStrategies, Infra} from 'scripts/payload/AaveV4Contracts.sol';

contract DiffPayload is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function spokeReserveConfigUpdates()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.ReserveConfigUpdate[] memory updates)
  {
    updates = new IAaveV4ConfigEngine.ReserveConfigUpdate[](8);
    updates[0] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.EURC,
      priceSource: 0xa6aB031A4d189B24628EC9Eb155F0a0f1A0E55a3,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    updates[1] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.MAIN_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDG,
      priceSource: 0xF29b1e3b68Fd59DD0a413811fD5d0AbaE653216d,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    updates[2] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.LOMBARD_BTC_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.LBTC,
      priceSource: 0x5C1771583dbbAE5AFEd71ACD2BfC0eA4029EBB04,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    updates[3] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDG,
      priceSource: 0xF29b1e3b68Fd59DD0a413811fD5d0AbaE653216d,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    updates[4] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.GOLD_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.EURC,
      priceSource: 0xa6aB031A4d189B24628EC9Eb155F0a0f1A0E55a3,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    updates[5] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.EURC,
      priceSource: 0xa6aB031A4d189B24628EC9Eb155F0a0f1A0E55a3,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    updates[6] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.FOREX_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.USDG,
      priceSource: 0xF29b1e3b68Fd59DD0a413811fD5d0AbaE653216d,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    updates[7] = IAaveV4ConfigEngine.ReserveConfigUpdate({
      spokeConfigurator: ISpokeConfigurator(Infra.SPOKE_CONFIGURATOR),
      spoke: Spokes.BLUECHIP_SPOKE,
      hub: Hubs.CORE_HUB,
      underlying: Tokens.EURC,
      priceSource: 0xa6aB031A4d189B24628EC9Eb155F0a0f1A0E55a3,
      collateralRisk: EngineFlags.KEEP_CURRENT,
      paused: EngineFlags.KEEP_CURRENT,
      frozen: EngineFlags.KEEP_CURRENT,
      borrowable: EngineFlags.KEEP_CURRENT,
      receiveSharesEnabled: EngineFlags.KEEP_CURRENT
    });
    return updates;
  }
}
