// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';

import {Hubs, Tokens, Infra} from 'scripts/payload/AaveV4Contracts.sol';

contract TokenizationSpokePayload is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function hubSpokeToAssetsAdditions()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.SpokeToAssetsAddition[] memory additions)
  {
    additions = new IAaveV4ConfigEngine.SpokeToAssetsAddition[](31);
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 250,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[0] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xd1dBB3275374ad63167Df9Dab75510B21F28aCDb,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.wstETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[1] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x96758bFe31c15CB82957F3326a50fAc8fad56084,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.weETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[2] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x4F8F51Da1A497C362eAd31c11bA826BC2CbA868E,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.rsETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[3] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x1a153Ed992cb3f87314bC79BE86159bBD5Ac46bb,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[4] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xaB5D8Ad884355F0D227Ef90DC953E6B0A4F5B789,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[5] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x73Fb187D6b4253B07eB1089173B01d9e84724bfA,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[6] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x504bcD783b9F53E3bd49D56643E56fd842e7e7d8,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.RLUSD,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[7] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x902915db5c2aB8bCaa76e72c2D0eF5D6c74CC70F,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDG,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[8] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xe6a389Da16ec8Db313391f804A992e05d600F050,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.frxUSD,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[9] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x3f52d398D1779d7801d19eEDdF56E463528B3434,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.EURC,
        config: IHub.SpokeConfig({
          addCap: 112500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[10] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xf0808539F533269f3c7e84ef351412fe2143F32e,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[11] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x77061a5D5cFfF2C59b11C34b1fC12b97Df7aDCC0,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.cbBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[12] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xE6DbefECDD2246a87a7218Dd7AcCa7c297530808,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.LBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[13] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x8e16005bc97B6a0febd9B89dd81b1f63AF936B50,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.XAUt,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[14] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xCDc2A2C11a18cbBc9B4aE10b7A598ce509F5dDDc,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.AAVE,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[15] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x00D7cD29A14B3f67bD4C865aDDDDfC94cA1b570C,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.LINK,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[16] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x4305066589259E191286f829807608bcf2425Ef9,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[17] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xB8DeA4dd8fE2FA5547148BC76E9A9C575D1E6c5D,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[18] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x0ED2E8d02cb592A3e81132E12B91b23C3f6109De,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.cbBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[19] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x859149eD6463E444d9E492c0AcbEc957943DA83c,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.wstETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[20] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xf2e654f1968843446CC2b4Fc05D70BF71F857e2F,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[21] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x984578F7470fF5F71526D26BD3607BbAB95C4fE4,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[22] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xf85528eD310a2B1F2b98DA743740f6A3f1038605,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[23] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x8ce41975BcA8bcE7F8F9aa7258b0aA2Bb89FE298,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_sUSDE_7MAY2026,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[24] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x9488964968Bba4bd28bf255E58aBD0588BfE2086,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_USDE_7MAY2026,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[25] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0xA770dfE60eE0813F3F76ac323AFe948E1193e3Ae,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.sUSDe,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[26] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0xB444B0a97Ecc67592Baf63c3Ebe46FB778e01eBd,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDe,
        config: IHub.SpokeConfig({
          addCap: 78000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[27] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x985e1aA0E0bDe8bf538e5695E2eeDf1D11c7CeD1,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[28] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0xef9ed8c801b1DBd68cb334ED32926C152AA660F7,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[29] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x57F897A56b807763683EAae3d82E19f8C755Df2D,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[30] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x109308A4602E3f45177F649CBa4a7e0d2984CA38,
        assets: assets
      });
    }
    return additions;
  }
}
