// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {Script} from 'forge-std/Script.sol';
import {TokenizationSpokeInstance} from 'src/spoke/instances/TokenizationSpokeInstance.sol';
import {TransparentUpgradeableProxy} from 'src/dependencies/openzeppelin/TransparentUpgradeableProxy.sol';
import {Hubs, Tokens} from 'scripts/payload/AaveV4Contracts.sol';

contract Factory {
  function create(
    address hub,
    address token,
    string memory name,
    string memory symbol,
    address proxyAdminOwner
  ) external returns (address) {
    address impl = address(new TokenizationSpokeInstance(hub, token));
    return
      address(
        new TransparentUpgradeableProxy(
          impl,
          proxyAdminOwner,
          abi.encodeCall(TokenizationSpokeInstance.initialize, (name, symbol))
        )
      );
  }
}

contract TokenizationSpokeDeploy is Script {
  function run() public {
    vm.startBroadcast();
    Factory factory = new Factory();
    (, address caller, ) = vm.readCallers();
    address proxy;

    // --- CORE_HUB ---
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.WETH,
      'Wrapped Aave Core WETH',
      'waCoreWETH',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'WETH', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.wstETH,
      'Wrapped Aave Core wstETH',
      'waCorewstETH',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'wstETH', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.weETH,
      'Wrapped Aave Core weETH',
      'waCoreweETH',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'weETH', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.rsETH,
      'Wrapped Aave Core rsETH',
      'waCorersETH',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'rsETH', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.USDT,
      'Wrapped Aave Core USDT',
      'waCoreUSDT',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'USDT', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.USDC,
      'Wrapped Aave Core USDC',
      'waCoreUSDC',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'USDC', proxy);
    proxy = factory.create(Hubs.CORE_HUB, Tokens.GHO, 'Wrapped Aave Core GHO', 'waCoreGHO', caller);
    vm.serializeAddress('CORE_HUB', 'GHO', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.RLUSD,
      'Wrapped Aave Core RLUSD',
      'waCoreRLUSD',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'RLUSD', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.USDG,
      'Wrapped Aave Core USDG',
      'waCoreUSDG',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'USDG', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.frxUSD,
      'Wrapped Aave Core frxUSD',
      'waCorefrxUSD',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'frxUSD', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.EURC,
      'Wrapped Aave Core EURC',
      'waCoreEURC',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'EURC', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.WBTC,
      'Wrapped Aave Core WBTC',
      'waCoreWBTC',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'WBTC', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.cbBTC,
      'Wrapped Aave Core cbBTC',
      'waCorecbBTC',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'cbBTC', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.LBTC,
      'Wrapped Aave Core LBTC',
      'waCoreLBTC',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'LBTC', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.XAUt,
      'Wrapped Aave Core XAUt',
      'waCoreXAUt',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'XAUt', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.AAVE,
      'Wrapped Aave Core AAVE',
      'waCoreAAVE',
      caller
    );
    vm.serializeAddress('CORE_HUB', 'AAVE', proxy);
    proxy = factory.create(
      Hubs.CORE_HUB,
      Tokens.LINK,
      'Wrapped Aave Core LINK',
      'waCoreLINK',
      caller
    );
    string memory core_hubJson = vm.serializeAddress('CORE_HUB', 'LINK', proxy);

    // --- PRIME_HUB ---
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.WETH,
      'Wrapped Aave Prime WETH',
      'waPrimeWETH',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'WETH', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.WBTC,
      'Wrapped Aave Prime WBTC',
      'waPrimeWBTC',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'WBTC', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.cbBTC,
      'Wrapped Aave Prime cbBTC',
      'waPrimecbBTC',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'cbBTC', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.wstETH,
      'Wrapped Aave Prime wstETH',
      'waPrimewstETH',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'wstETH', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.USDC,
      'Wrapped Aave Prime USDC',
      'waPrimeUSDC',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'USDC', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.USDT,
      'Wrapped Aave Prime USDT',
      'waPrimeUSDT',
      caller
    );
    vm.serializeAddress('PRIME_HUB', 'USDT', proxy);
    proxy = factory.create(
      Hubs.PRIME_HUB,
      Tokens.GHO,
      'Wrapped Aave Prime GHO',
      'waPrimeGHO',
      caller
    );
    string memory prime_hubJson = vm.serializeAddress('PRIME_HUB', 'GHO', proxy);

    // --- PLUS_HUB ---
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.PT_sUSDE_7MAY2026,
      'Tokenized Aave Plus PT_sUSDE_7MAY2026',
      'aPlus-PT_sUSDE_7MAY2026',
      caller
    );
    vm.serializeAddress('PLUS_HUB', 'PT_sUSDE_7MAY2026', proxy);
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.PT_USDE_7MAY2026,
      'Tokenized Aave Plus PT_USDE_7MAY2026',
      'aPlus-PT_USDE_7MAY2026',
      caller
    );
    vm.serializeAddress('PLUS_HUB', 'PT_USDE_7MAY2026', proxy);
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.sUSDe,
      'Wrapped Aave Plus sUSDe',
      'waPlussUSDe',
      caller
    );
    vm.serializeAddress('PLUS_HUB', 'sUSDe', proxy);
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.USDe,
      'Wrapped Aave Plus USDe',
      'waPlusUSDe',
      caller
    );
    vm.serializeAddress('PLUS_HUB', 'USDe', proxy);
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.USDC,
      'Wrapped Aave Plus USDC',
      'waPlusUSDC',
      caller
    );
    vm.serializeAddress('PLUS_HUB', 'USDC', proxy);
    proxy = factory.create(Hubs.PLUS_HUB, Tokens.GHO, 'Wrapped Aave Plus GHO', 'waPlusGHO', caller);
    vm.serializeAddress('PLUS_HUB', 'GHO', proxy);
    proxy = factory.create(
      Hubs.PLUS_HUB,
      Tokens.USDT,
      'Wrapped Aave Plus USDT',
      'waPlusUSDT',
      caller
    );
    string memory plus_hubJson = vm.serializeAddress('PLUS_HUB', 'USDT', proxy);

    vm.stopBroadcast();

    vm.serializeString('root', 'CORE_HUB', core_hubJson);
    vm.serializeString('root', 'PRIME_HUB', prime_hubJson);
    string memory finalJson = vm.serializeString('root', 'PLUS_HUB', plus_hubJson);
    vm.writeJson(finalJson, 'scripts/config/tokenization-deploy.json');
  }
}
