// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

import {AaveV4Payload} from 'src/config-engine/AaveV4Payload.sol';
import {IAaveV4ConfigEngine} from 'src/config-engine/interfaces/IAaveV4ConfigEngine.sol';
import {IHubConfigurator} from 'src/hub/interfaces/IHubConfigurator.sol';
import {IHub} from 'src/hub/interfaces/IHub.sol';

import {Hubs, Tokens, Infra} from 'scripts/payload/AaveV4Contracts.sol';

contract TokenizationSpokePayload is AaveV4Payload {
  constructor(IAaveV4ConfigEngine configEngine) AaveV4Payload(configEngine) {}

  function hubSpokeToAssetsAdditions()
    public
    pure
    override
    returns (IAaveV4ConfigEngine.SpokeToAssetsAddition[] memory additions)
  {
    additions = new IAaveV4ConfigEngine.SpokeToAssetsAddition[](31);
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 250,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[0] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x7320CF22Ac095bA2a2e0a652F77efB836c2E751b,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.wstETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[1] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xcb0E7dA9c635628f6d4827355AeCa75aB8d3560f,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.weETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[2] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x559cEc2C840D9DBB18936Afc5E5341D78bfC7Cbe,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.rsETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[3] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x45a04Ca1A5cbEeA4B44356c75EDd29b33eB2527a,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[4] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x5eC44a70F309854fe04d495cFE1B5dA63DD1cc73,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 312500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[5] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x531E90a2376902DE8915789Fcc1075e3B0c153E7,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[6] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x58C14a5E061c9bC6926c5b853445290F296C2F7B,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.RLUSD,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[7] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xC8a125AE4275a78AADc53B46Ca10566Bc9B249E0,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDG,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[8] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xAC2435E3C25e8246870D33ce0a26988A46d5DB68,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.frxUSD,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[9] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x2226749630775ee20230Ad65214fB339087eF30D,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.EURC,
        config: IHub.SpokeConfig({
          addCap: 112500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[10] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x6D9e2Cdd61CaF69af99b275704B6e272C41c6718,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[11] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x82A9CC4656784E55Ef2E78F704028B5E1Bfc1732,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.cbBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[12] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x33B41B74366F55327d959FfF6D6b6fBc2853dbB1,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.LBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[13] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x7961F140B570490849DB878AE222570ea838799d,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.XAUt,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[14] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x4E712562fcb5337011398B6C630f55b60641cd5e,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.AAVE,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[15] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0x0A65197b16C5969F92672051c9C9C0C75B369135,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.LINK,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[16] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.CORE_HUB,
        spoke: 0xE69C2045095C8Ab3E2a7d77de2328faE5baF797c,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[17] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x2087513383330B961A3753B47627Bbf149F31c70,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.WBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[18] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x5AE3d87De89CA6Ce501e8317887F71EABED69E18,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.cbBTC,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[19] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xD38098faf52D8E915EdED84fBF30F81C17906938,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.wstETH,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[20] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0xFCD3D3C69cd032DE0cc78fE529B7447D2fe7F666,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[21] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x486415fb1F8b062c89ED548f871cf64304AACb31,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[22] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x46c588DD8453aC259c1f6a54b4C9A93C2aC3762D,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[23] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PRIME_HUB,
        spoke: 0x900fD46d565d1ac8995928c0179052ec02a6D0E1,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_sUSDE_7MAY2026,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[24] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x90774889c22D2F2Adf44da1f04C7c95542590df4,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.PT_USDE_7MAY2026,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[25] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0xdd2Eb78BF9e6aC5068B95aD2d451e8c9Af10ac81,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.sUSDe,
        config: IHub.SpokeConfig({
          addCap: 0,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[26] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x24f8c062e1E0451736C1D6E023510DA262a41df4,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDe,
        config: IHub.SpokeConfig({
          addCap: 78000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[27] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x502Cd81da6a8F1785eb2eEE72713B7388E16A854,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDC,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[28] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0xc94bdd83D2c7655C280655D60954e79E88D4F949,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.GHO,
        config: IHub.SpokeConfig({
          addCap: 125000,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[29] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0xA54382db40EC602c0a173A08f9E86Ed40F9D4D10,
        assets: assets
      });
    }
    {
      IAaveV4ConfigEngine.SpokeAssetConfig[]
        memory assets = new IAaveV4ConfigEngine.SpokeAssetConfig[](1);
      assets[0] = IAaveV4ConfigEngine.SpokeAssetConfig({
        underlying: Tokens.USDT,
        config: IHub.SpokeConfig({
          addCap: 37500,
          drawCap: 0,
          riskPremiumThreshold: 0,
          active: true,
          halted: false
        })
      });
      additions[30] = IAaveV4ConfigEngine.SpokeToAssetsAddition({
        hubConfigurator: IHubConfigurator(Infra.HUB_CONFIGURATOR),
        hub: Hubs.PLUS_HUB,
        spoke: 0x80835EB50694EE0e519743f67e5401e6FD300006,
        assets: assets
      });
    }
    return additions;
  }
}
