import fs from 'fs';
import path from 'path';
import {getAddress} from 'viem';

const chain = process.argv[2];
if (!chain) {
  console.error('Usage: bun run generateContracts.ts <chain>');
  process.exit(1);
}

const ROOT = path.resolve(__dirname, '..', '..', 'config');
const deploy = JSON.parse(fs.readFileSync(path.join(ROOT, `${chain}.json`), 'utf8'));
const config = JSON.parse(fs.readFileSync(path.join(ROOT, 'config.json'), 'utf8'));
const tokenAddresses = Object.fromEntries(
  Object.entries(config.tokens).map(([key, val]: [string, any]) => [key, val.address]),
);

function sanitizeKey(key: string) {
  if (/^\d/.test(key)) return '_' + key;
  return key;
}

function generateLibrary(name: string, entries: Record<string, string>) {
  const lines = Object.entries(entries).map(
    ([key, addr]) => `  address internal constant ${sanitizeKey(key)} = ${getAddress(addr)};`,
  );
  return `library ${name} {\n${lines.join('\n')}\n}`;
}

const libraries: string[] = [];

const mapFields: [string, string][] = [
  ['Hubs', 'hub'],
  ['Spokes', 'spoke'],
  ['IrStrategies', 'irStrategy'],
  ['Oracles', 'oracle'],
];

for (const [libName, field] of mapFields) {
  if (deploy[field]) {
    libraries.push(generateLibrary(libName, deploy[field]));
  }
}

libraries.push(generateLibrary('Tokens', tokenAddresses));

const infraEntries: Record<string, string> = {
  HUB_CONFIGURATOR: deploy.hubConfigurator,
  SPOKE_CONFIGURATOR: deploy.spokeConfigurator,
  ACCESS_MANAGER: deploy.accessManager,
  CONFIG_POSITION_MANAGER: deploy.configPositionManager,
  GIVER_POSITION_MANAGER: deploy.giverPositionManager,
  TAKER_POSITION_MANAGER: deploy.takerPositionManager,
  NATIVE_TOKEN_GATEWAY: deploy.nativeTokenGateway,
  SIGNATURE_GATEWAY: deploy.signatureGateway,
  TREASURY_SPOKE: deploy.treasurySpoke,
};

libraries.push(generateLibrary('Infra', infraEntries));

const output = `// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

${libraries.join('\n\n')}
`;

const outDir = path.join(__dirname, '..');
fs.mkdirSync(outDir, {recursive: true});
fs.writeFileSync(path.join(outDir, 'AaveV4Contracts.sol'), output);
console.log('Generated scripts/payload/AaveV4Contracts.sol');
