const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..", "..", "config");
const deploy = JSON.parse(
  fs.readFileSync(path.join(ROOT, "deploy.json"), "utf8"),
);
const config = JSON.parse(
  fs.readFileSync(path.join(ROOT, "config.json"), "utf8"),
);
const tokenAddresses = Object.fromEntries(
  Object.entries(config.tokens).map(([key, val]) => [key, val.address]),
);

function sanitizeKey(key) {
  // Solidity identifiers cannot start with a digit
  if (/^\d/.test(key)) return "_" + key;
  return key;
}

(async () => {
  const { getAddress } = await import("viem");

  function generateLibrary(name, entries) {
    const lines = Object.entries(entries).map(
      ([key, addr]) =>
        `  address internal constant ${sanitizeKey(key)} = ${getAddress(addr)};`,
    );
    return `library ${name} {\n${lines.join("\n")}\n}`;
  }

  const libraries = [];

  // Map-type fields
  const mapFields = [
    ["Hubs", "hub"],
    ["Spokes", "spoke"],
    ["IrStrategies", "irStrategy"],
    ["Oracles", "oracle"],
  ];

  for (const [libName, field] of mapFields) {
    if (deploy[field]) {
      libraries.push(generateLibrary(libName, deploy[field]));
    }
  }

  libraries.push(generateLibrary("Tokens", tokenAddresses));

  // Single-address fields -> Infra library
  const infraEntries = {
    HUB_CONFIGURATOR: deploy.hubConfigurator,
    SPOKE_CONFIGURATOR: deploy.spokeConfigurator,
    ACCESS_MANAGER: deploy.accessManager,
    CONFIG_POSITION_MANAGER: deploy.configPositionManager,
    GIVER_POSITION_MANAGER: deploy.giverPositionManager,
    TAKER_POSITION_MANAGER: deploy.takerPositionManager,
    NATIVE_TOKEN_GATEWAY: deploy.nativeTokenGateway,
    SIGNATURE_GATEWAY: deploy.signatureGateway,
    TREASURY_SPOKE: deploy.treasurySpoke,
  };

  libraries.push(generateLibrary("Infra", infraEntries));

  const output = `// SPDX-License-Identifier: UNLICENSED
// AUTOGENERATED - DO NOT EDIT
pragma solidity ^0.8.0;

${libraries.join("\n\n")}
`;

  const outDir = path.join(__dirname, "..");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "AaveV4Contracts.sol"), output);
  console.log("Generated scripts/output/AaveV4Contracts.sol");
})();
